### ISSUE TITLE
Cucumber does not automatically re-run after server restart

### ISSUE THREAD

**Issue by orlade** [xolvio/meteor-cucumber#117]
When I start Meteor with Cucumber, it runs nicely, and changing tests causes it to re-run, but when I change something that causes the Meteor server to restart (including changing my Cucumber fixtures file), the mirror restarts too, but Cucumber is not restarted.

The Meteor server says:

```
I20150528-01:37:37.391(10)? [velocity] Mirror registered. Handshaking with mirror...
I20150528-01:37:37.399(10)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
I20150528-01:37:37.399(10)?   port: '46295',
I20150528-01:37:37.399(10)?   host: 'http://localhost:46295/' }
```

The Cucumber log says:

```
[sanjo:long-running-child-process]: Exposing imports for testing purposes
[velocity] Mirror detected - Not adding velocity core
[velocity] Not adding mirror-registry because NODE_ENV is development  and IS_MIRROR is true
[velocity] Starting mirror on port 46295
[xolvio:cucumber] Mirror server is initializing
[xolvio:cucumber] Starting Chimp
[xolvio:cucumber] Chimp is already running in server mode
=> Meteor server restarted
[velocity] Mirror started. Connecting via DDP to parent
[velocity] Mirror connected to parent. Registering mirror...
[velocity] Established connection with Velocity.
```

And then nothing happens. This is running xolvio:cucumber@0.8.5 on Ubuntu 14 (4 and 10).

**Comment by orlade** [comment]
I just noticed that if I terminate the Meteor server quickly after the restart, the log throws an error:

```
Exception while invoking method 'login' Error: No replica set primary available for query with ReadPreference PRIMARY
    at Object.Future.wait (/home/oliver/.meteor/packages/velocity_meteor-tool/.1.1.3_4.1t47rfi++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
    at [object Object]._.extend._nextObject (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:961:47)
    at [object Object]._.extend.forEach (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:995:22)
    at [object Object]._.extend.map (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:1005:10)
    at [object Object]._.extend.fetch (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:1029:17)
    at [object Object].Cursor.(anonymous function) (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:844:44)
    at [object Object].cursorProto.(anonymous function) [as fetch] (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2165:32)
    at [object Object].MongoConnection.findOne (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:750:56)
    at Object.Collection (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:665:16)
    at Object.collection.(anonymous function) [as findOne] (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:127:21)
    at [object Object]._.extend.findOne (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:3643:29)
    at [object Object].Accounts._generateStampedLoginToken.token (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:997:27)
    at /tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:615:32
    at tryLoginMethod (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:418:14)
    at runLoginHandlers (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:612:18)
    at [object Object].Meteor.methods.login (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:666:18)
    - - - - -
    at [object Object].ReplSet.checkoutReader (/home/oliver/.meteor/packages/mongo/.1.1.0.jntven++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
    at Cursor.nextObject (/home/oliver/.meteor/packages/mongo/.1.1.0.jntven++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
    at [object Object].fn [as _synchronousNextObject] (/home/oliver/.meteor/packages/velocity_meteor-tool/.1.1.3_4.1t47rfi++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:89:26)
    at [object Object]._.extend._nextObject (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:961:22)
    at [object Object]._.extend.forEach (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:995:22)
    at [object Object]._.extend.map (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:1005:10)
    at [object Object]._.extend.fetch (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:1029:17)
    at [object Object].Cursor.(anonymous function) (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:844:44)
    at [object Object].cursorProto.(anonymous function) [as fetch] (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2165:32)
    at [object Object].MongoConnection.findOne (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:750:56)
    at Object.Collection (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:665:16)
    at Object.collection.(anonymous function) [as findOne] (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:127:21)
    at [object Object]._.extend.findOne (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/mongo.js:3643:29)
    at [object Object].Accounts._generateStampedLoginToken.token (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:997:27)
    at /tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:615:32
    at tryLoginMethod (/tmp/meteor-test-runjlqcmj/.meteor/local/build/programs/server/packages/accounts-base.js:418:14)
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
Parent process ( 3515 ) is dead! Exiting cucumber
```

I saw some mention about a similar issue and something about login somewhere else, though I can't find it now...

**Comment by samhatoum** [comment]
Thank you, I just noticed this. will have a fix out today
