### ISSUE TITLE
Cucumber BeforeFeatures hook had error

### ISSUE THREAD

**Issue by sailesh** [xolvio/meteor-cucumber#119]
I have a before hook as below which resets a db
```
var reset = function () {
  this.Before(function (callback) {
    // "global.server.call('resetdb', callback);" as per https://github.com/xolvio/meteor-cucumber
    // does not work use "this.server.call('resetdb', callback);"
    this.server.call('resetdb', callback);
  });
};

module.exports = reset;
```
When I start meteor with cucumber the first run is successful, but if I change a test/code which causes it to rerun/restart it produces the following error and fails,

```
[xolvio:cucumber] Running in batch-features mode.
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object already exists, not creating a new one
[chimp][selenium] Start
[chimp][selenium] Already running, doing nothing
[chimp][cucumber] Running
[chimp][world] creating DDP connection
[chimp][hooks] Starting BeforeFeatures
[chimp][world] getting browser
[chimp][session-manager] options are { port: '49922', browser: 'firefox', deviceName: undefined }
[chimp][session-manager] created a new SessionManager { port: '49922', browser: 'firefox', deviceName: undefined }
[chimp][world] custom chimp.js not found, loading defaults
[chimp][world] webdriverOptions are  {"waitforTimeout":10000,"desiredCapabilities":{"browserName":"firefox","platform":"ANY","name":""},"host":"localhost","port":"49922","logLevel":"silent"}
[chimp][session-manager] creating webdriver remote 
[chimp][session-manager] checking connection to selenium server
[chimp][session-manager] requesting sessions from http://localhost:49922/wd/hub/sessions
[chimp][selenium.stderr] 13:50:23.051 INFO - Executing: org.openqa.selenium.remote.server.handler.GetAllSessions@35a9b86e)

[chimp][selenium.stderr] 13:50:23.051 INFO - Done: org.openqa.selenium.remote.server.handler.GetAllSessions@35a9b86e

[chimp][session-manager] received data {"sessionId":null,"status":0,"state":"success","value":[{"id":"c0d8bbfa-8f88-4360-a413-9e9963a76446","class":"org.openqa.selenium.remote.server.handler.GetAllSessions$SessionInfo","capabilities":{"platform":"LINUX","acceptSslCerts":true,"javascriptEnabled":true,"browserName":"firefox","rotatable":false,"locationContextEnabled":true,"version":"38.0","cssSelectorsEnabled":true,"databaseEnabled":true,"handlesAlerts":true,"nativeEvents":false,"webStorageEnabled":true,"applicationCacheEnabled":true,"takesScreenshot":true},"hCode":428562760}],"class":"org.openqa.selenium.remote.Response","hCode":194155282}
[chimp][session-manager] Found an open selenium sessions, reusing session c0d8bbfa-8f88-4360-a413-9e9963a76446
[chimp][session-manager] Did not find any open selenium sessions, not reusing a session
[chimp][session-manager] monkey patching the browser object
[chimp][hooks] init browser
[chimp][session-manager] browser already initialized
[chimp][hooks] init browser callback
[chimp][hooks] setup DDP
[chimp][hooks] connecting via DDP to http://localhost:41716/
[chimp][hooks] BeforeFeatures hook had error
[TypeError: Object #<Object> has no method 'timeoutsAsyncScript']
[chimp][cucumber] Closed with code 2
[chimp] finished rerun
[chimp] Finished running async processes with errors
[xolvio:cucumber] Bad response from Chimp server.
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] killing child process with pid 10163
[chimp] Finished interrupting processes
```

.meteor/versions
```
accounts-base@1.2.0
accounts-facebook@1.0.4
accounts-google@1.0.4
accounts-oauth@1.1.5
accounts-password@1.1.1
accounts-ui@1.1.5
accounts-ui-unstyled@1.1.7
aldeed:autoform@4.2.2
aldeed:collection2@2.3.3
aldeed:simple-schema@1.3.2
aldeed:template-extension@3.4.3
amplify@1.0.0
autoupdate@1.2.1
babrahams:editable-json@0.4.3
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cfs:access-point@0.1.47
cfs:base-package@0.0.29
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:ejson-file@0.1.4
cfs:file@0.1.17
cfs:filesystem@0.1.2
cfs:gridfs@0.0.33
cfs:http-methods@0.0.28
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.8
cfs:storage-adapter@0.2.2
cfs:tempstore@0.1.5
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.0.5
coffeescript@1.0.6
dandv:caret-position@2.1.1
dburles:collection-helpers@1.0.3
dburles:mongo-collection-instances@0.3.3
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
facebook@1.2.0
fastclick@1.0.3
fortawesome:fontawesome@4.3.0
francocatena:status@1.1.2
gadicohen:phantomjs@0.0.2
geojson-utils@1.0.3
google@1.1.5
ground:db@0.3.7
ground:dictionary@0.2.0
ground:localstorage@0.1.8
ground:minimax@1.1.2
ground:servertime@0.0.3
ground:store@0.1.1
ground:util@0.1.13
gwendall:session-json@0.1.7
harrison:papa-parse@1.1.0
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3_2
json@1.0.3
kevohagan:sweetalert@0.5.0
lai:collection-extensions@0.1.3
launch-screen@1.0.2
lepozepo:accounting@1.0.0
less@1.0.14
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
meteorhacks:subs-manager@1.3.0
meteortoys:toykit@0.5.0
mike:mocha@0.5.4
minifiers@1.1.5
minimongo@1.0.8
mizzao:autocomplete@0.5.1
mizzao:timesync@0.3.1
mobile-status-bar@1.0.3
momentjs:moment@2.10.2
mongo@1.1.0
mongo-livedata@1.0.8
msavin:mongol@1.0.70
mystor:device-detection@0.2.0
natestrauser:select2@3.5.1
npm-bcrypt@0.7.8_2
oauth@1.1.4
oauth2@1.1.3
observe-sequence@1.0.6
ordered-dict@1.0.3
package-version-parser@3.0.3
peerlibrary:assert@0.2.5
peerlibrary:blocking@0.5.2
peerlibrary:fs@0.1.7
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
raix:eventemitter@0.1.2
raix:onetimeout@1.0.3
raix:stubfence@1.0.1
rajit:bootstrap3-datepicker@1.4.1
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
reywood:publish-composite@1.3.6
routepolicy@1.0.5
sacha:spin@2.0.4
sanjo:long-running-child-process@1.1.1
sanjo:meteor-files-helpers@1.1.0_4
sanjo:meteor-version@1.0.0
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.6
spiderable@1.0.7
srp@1.0.3
summernote:summernote@0.6.0_1
tap:i18n@1.3.2
templating@1.1.1
tracker@1.0.7
twbs:bootstrap@3.3.4
ui@1.0.6
underscore@1.0.3
url@1.0.4
velocity:chokidar@1.0.1_1
velocity:core@0.6.5
velocity:html-reporter@0.6.2
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.8.7
```
.meteor/packages
```
meteor-platform
aldeed:collection2
iron:router
meteorhacks:subs-manager
accounts-base
accounts-password
mystor:device-detection
sacha:spin
mizzao:timesync
jquery
momentjs:moment
lepozepo:accounting
cfs:standard-packages
cfs:filesystem
cfs:ejson-file
cfs:gridfs
twbs:bootstrap
francocatena:status
accounts-facebook
accounts-google
service-configuration
fortawesome:fontawesome
ground:db
aldeed:autoform
mizzao:autocomplete
peerlibrary:fs
spiderable
gadicohen:phantomjs
natestrauser:select2
dburles:collection-helpers
rajit:bootstrap3-datepicker
summernote:summernote
email
accounts-ui
reywood:publish-composite
kevohagan:sweetalert
tap:i18n
msavin:mongol
harrison:papa-parse
xolvio:cucumber@=0.8.7
mike:mocha
```

**Comment by samhatoum** [comment]
thanks for reporting, I think I know what this is. Maybe you can use phantom in the meantime if that works for you

**Comment by sailesh** [comment]
Thanks sam, i just realized that the error is not related to the hook I mentioned in the report. Figured it is to do with SELENIUM_BROWSER=firefox

The reason I am using firefox for this test is because I couldn't get  http://webdriver.io/api/utility/chooseFile.html to work on phantom yet.

**Comment by frosario** [comment]
+1 ^
Having the same issue while running with `SELENIUM_BROWSER=firefox`

**Comment by samhatoum** [comment]
you need to remove xolvio:webdriver, let me know if that helps.

**Comment by frosario** [comment]
Upgraded to xolvio:cucumber version 0.9.2
Removed xolvio:webdriver

```Unhandled rejection Error: [object Object]
  at Promise.b (domain.js:183:18)
From previous event:
  at WebdriverIO.<anonymous> (/home/vagrant/rana/tests/cucumber/features/support/hooks.js:111:15)
  at /home/vagrant/.meteor/packages/xolvio_cucumber/.0.9.2.9m898o++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/chainit/index.js:146:12
  at process._tickDomainCallback (node.js:486:13)```

**Comment by samhatoum** [comment]
@frosario It's difficult for me to know what's happening from your report. I'll need more info. Please create a new issue and see the contributing guidelines I just added. Thanks :)

**Comment by frosario** [comment]
No worries. Thanks :)
