### ISSUE TITLE
Couldn't connect to selenium driver

### ISSUE THREAD

**Issue by jhartma** [xolvio/meteor-cucumber#120]
I am running the 0.8.7 version. This is the test code 
```javascript
this.Given(/^I am logged in as "([^"]*)" with password "([^"]*)"$/, function(username, password, callback) {
  this.client.executeAsync(function(done) {
    Meteor.loginWithPassword(username, password, function(err, res) {
      done(res);
    });
  }, function(err, res) {
    callback();
  });
});
```

and the output
```
[xolvio:cucumber] Cucumber is running

Feature: Navigation on the dashboard

  As a logged in user
  I want to visit the dashboard
  So that I can navigate to other pages

  @dev
  Scenario: Users can navigate to the documents page   # features/dashboard.feature:14
    Given I am logged in as "jh" with password "test"  # features/dashboard.feature:10
    And I am on the dashboard page                     # features/dashboard.feature:11
    And the dashboard page has a menubar               # features/dashboard.feature:12
    Given there is a link called "Documents"           # features/dashboard.feature:15
    When I click on the link                           # features/dashboard.feature:16
    Then I am redirected to a page called "documents"  # features/dashboard.feature:17


Feature: Visit the landing page

  As a visitor
  I want to visit the landing page
  So that I can see what's on the page

  @dev
  Scenario: Visitors can reach the landing page   # features/landingPage.feature:9
    Given I am a new visitor                      # features/landingPage.feature:10
    When I navigate to the landing page           # features/landingPage.feature:11
      RuntimeError: RuntimeError
           (ECONNREFUSED:-1) Couldn't connect to selenium server
           Problem: Couldn't connect to selenium server

           Callstack:
           -> url("http://localhost:56727/","/")

    Then I see the title "sci:hub"                # features/landingPage.feature:12


Feature: Login as a user

  As a registered user
  I want to visit the landing page
  So that I can login

  @dev
  Scenario: Registered users can login                       # features/login.feature:9
    Given I am a user with username "jh" and password "test" # features/login.feature:10
    And I am logged out                                      # features/login.feature:11
    When I navigate to the landing page                      # features/login.feature:12
      RuntimeError: RuntimeError
           (ECONNREFUSED:-1) Couldn't connect to selenium server
           Problem: Couldn't connect to selenium server

           Callstack:
           -> url("http://localhost:56727/","/")

    And login with my username "jh" and password "test"      # features/login.feature:13
    Then I am redirected to the dashboard                    # features/login.feature:14


(::) failed steps (::)

RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:56727/","/")


RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:56727/","/")
```

The funny thing is, the problem only occurs when I add the above test code with the Meteor.loginWithPassword call. In fact, whatever Meteor.* I use crashes the tests. The test itself runs through but then the following tests fail. Before, they just worked and they contain Meteor.call as well.
Am I doing something wrong here? 

I looked through the other issues but nothing worked. Using the chrome driver doesnt work either, in fact the chrome driver doesnt work at all, don't know if that's because I'm on a linux box.

**Comment by jhartma** [comment]
Wow, thanks for the immediate response! Here is output
```
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][phantom] starting process
[chimp][phantom.stdout] PhantomJS is launching GhostDriver...

[chimp][phantom.stdout] [INFO  - 2015-05-30T17:39:23.312Z] GhostDriver - Main - running on port 43034

[chimp][phantom] started successfully
[chimp][cucumber] Running
[chimp][world] creating DDP connection
[chimp][hooks] Starting BeforeFeatures
[chimp][world] getting browser
[chimp][session-manager] options are { port: '43034', browser: 'phantomjs', deviceName: undefined }
[chimp][session-manager] created a new SessionManager { port: '43034', browser: 'phantomjs', deviceName: undefined }
[chimp][world] custom chimp.js not found, loading defaults
[chimp][world] webdriverOptions are  {"waitforTimeout":10000,"desiredCapabilities":{"browserName":"phantomjs","platform":"ANY","name":""},"host":"localhost","port":"43034","logLevel":"silent"}
[chimp][session-manager] creating webdriver remote 
[chimp][session-manager] checking connection to selenium server
[chimp][session-manager] browser is phantomjs, not reusing a session
[chimp][hooks] init browser
[chimp][hooks] setup DDP
[chimp][hooks] connecting via DDP to http://localhost:54830/
[chimp][phantom.stdout] [INFO  - 2015-05-30T17:39:24.493Z] Session [cfec2480-06f2-11e5-ac94-ad962f545eaa] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}

[chimp][phantom.stdout] [INFO  - 2015-05-30T17:39:24.493Z] Session [cfec2480-06f2-11e5-ac94-ad962f545eaa] - page.customHeaders:  - {}
[INFO  - 2015-05-30T17:39:24.493Z] Session [cfec2480-06f2-11e5-ac94-ad962f545eaa] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-05-30T17:39:24.493Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: cfec2480-06f2-11e5-ac94-ad962f545eaa

[chimp][hooks] init browser callback
[chimp][hooks] Finished BeforeFeatures
[chimp][hooks] User-defined BeforeFeatures not found, finishing up

Feature: Navigation on the dashboard

  As a logged in user
  I want to visit the dashboard
  So that I can navigate to other pages

[chimp][world] setting up world
  @dev
  Scenario: Users can navigate to the documents page   # features/dashboard.feature:14
    Given I am logged in as "jh" with password "test"  # features/dashboard.feature:10
    And I am on the dashboard page                     # features/dashboard.feature:11
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/0-step_failed_1433007564667.png
[chimp][hooks] saved screenshot to 0-step_failed_1433007564667.png
    And the dashboard page has a menubar               # features/dashboard.feature:12
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/1-step_failed_1433007564803.png
[chimp][hooks] saved screenshot to 1-step_failed_1433007564803.png
    Given there is a link called "Documents"           # features/dashboard.feature:15
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/2-step_failed_1433007564938.png
[chimp][hooks] saved screenshot to 2-step_failed_1433007564938.png
    When I click on the link                           # features/dashboard.feature:16
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/3-step_failed_1433007565068.png
[chimp][hooks] saved screenshot to 3-step_failed_1433007565068.png
    Then I am redirected to a page called "documents"  # features/dashboard.feature:17
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/4-step_failed_1433007565197.png
[chimp][hooks] saved screenshot to 4-step_failed_1433007565197.png


Feature: Visit the landing page

  As a visitor
  I want to visit the landing page
  So that I can see what's on the page

[chimp][world] setting up world
  @dev
  Scenario: Visitors can reach the landing page   # features/landingPage.feature:9
    Given I am a new visitor                      # features/landingPage.feature:10
[chimp][phantom.stderr] PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/492e8c3d-9df8-5ebf-252e8c10-35495104.dmp

    When I navigate to the landing page           # features/landingPage.feature:11
      RuntimeError: RuntimeError
           (ECONNREFUSED:-1) Couldn't connect to selenium server
           Problem: Couldn't connect to selenium server

           Callstack:
           -> url("http://localhost:54830/","/")

[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/5-step_failed_1433007566886.png
[chimp][hooks] saved screenshot to 5-step_failed_1433007566886.png
    Then I see the title "sci:hub"                # features/landingPage.feature:12
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/6-step_failed_1433007566890.png
[chimp][hooks] saved screenshot to 6-step_failed_1433007566890.png


Feature: Login as a user

  As a registered user
  I want to visit the landing page
  So that I can login

[chimp][world] setting up world
  @dev
  Scenario: Registered users can login                       # features/login.feature:9
    Given I am a user with username "jh" and password "test" # features/login.feature:10
    And I am logged out                                      # features/login.feature:11
    When I navigate to the landing page                      # features/login.feature:12
      RuntimeError: RuntimeError
           (ECONNREFUSED:-1) Couldn't connect to selenium server
           Problem: Couldn't connect to selenium server

           Callstack:
           -> url("http://localhost:54830/","/")

[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/7-step_failed_1433007566900.png
[chimp][hooks] saved screenshot to 7-step_failed_1433007566900.png
    And login with my username "jh" and password "test"      # features/login.feature:13
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/8-step_failed_1433007566902.png
[chimp][hooks] saved screenshot to 8-step_failed_1433007566902.png
    Then I am redirected to the dashboard                    # features/login.feature:14
[chimp][hooks] step failed - capturing screenshot
[chimp][hooks] saving screenshot to /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots/9-step_failed_1433007566904.png
[chimp][hooks] saved screenshot to 9-step_failed_1433007566904.png


(::) failed steps (::)

RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:54830/","/")


RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:54830/","/")


Failing scenarios:
/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features/landingPage.feature:9 # Scenario: Visitors can reach the landing page
/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features/login.feature:9 # Scenario: Registered users can login

3 scenarios (2 failed, 1 pending)
14 steps (2 failed, 1 pending, 7 skipped, 4 passed)
[chimp][hooks] Starting AfterFeatures
[chimp][hooks] Ending browser session
[chimp][hooks] Finished AfterFeatures
[chimp][cucumber] Closed with code 2
[chimp] finished rerun
[chimp] Finished running async processes with errors
RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:54830/","/")

RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> url("http://localhost:54830/","/")
```

**Comment by samhatoum** [comment]
are you navigating to the mirror URL first?

try changing your method from
`this.client.executeAsync(...` to `this.client.url(process.env.ROOT_URL).executeAsync`

**Comment by samhatoum** [comment]
Odd that chromedriver doesn't work. If that issue persists, could you please file a bug report for it with a debug log of what happens trying to start chrome?

**Comment by jhartma** [comment]
Navigating to the mirror URL first makes the test run through completely, awesome! Didn't know I had to do this.

And with the chromedriver, I don't know, maybe it's my setup, or is it shipped with the cucumber package? It's not really an issue for me, but here is the output of ```VELOCITY_DEBUG=1 SELENIUM_BROWSER=chrome meteor ``` if you're interested

```
tail: /home/knut/Dokumente/Programming/meteor/playground/app/.meteor/local/log/cucumber.log: Datei abgeschnitten
Spawn script arguments:
parentPid: 16952
taskName: cucumber
command: meteor
commandArguments: [ 'run',
  '--test-app',
  '--port',
  '48271',
  '--include-tests',
  'cucumber/fixtures',
  '--settings',
  '/tmp/tmp-17036GSWXIXHkUA3F.tmp',
  '--raw-logs',
  '--release',
  'velocity:METEOR@1.1.0.2_3' ]
pid: 17063
child.pid: 17065
=> Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)

[[[[[ ~/Dokumente/Programming/meteor/playground/app ]]]]]

=> Started proxy.
[sanjo:long-running-child-process]: Exposing imports for testing purposes
[velocity] Mirror detected - Not adding velocity core
[velocity] Not adding mirror-registry because NODE_ENV is development  and IS_MIRROR is true
[velocity] Starting mirror on port 48271
[xolvio:cucumber] Mirror server is initializing
[xolvio:cucumber] Starting Chimp
[xolvio:cucumber] Screenshots dir is /home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots
[xolvio:cucumber] Starting Chimp with /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp [ '/home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp',
  '-r',
  '/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features',
  '--snippets',
  '--ddp=http://localhost:48271/',
  '--log=error',
  '--debug',
  '--screenshotsPath=/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots',
  '--tags=@dev',
  '--browser=chrome',
  '--server',
  '--serverPort=8866' ] { cwd: '/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber',
  stdio: 'inherit',
  env: 
   { GREP_COLOR: '37;45',
     XDG_VTNR: '2',
     LESS_TERMCAP_mb: '\u001b[01;31m',
     XDG_SESSION_ID: 'c3',
     KDE_MULTIHEAD: 'false',
     METEOR_SHELL_DIR: '/tmp/meteor-test-run2hm9u4/.meteor/local/shell',
     LESS_TERMCAP_md: '\u001b[01;31m',
     LESS_TERMCAP_me: '\u001b[0m',
     MIRROR_PORT: '48271',
     SHELL: '/usr/bin/zsh',
     TERM: 'xterm',
     IS_MIRROR: 'true',
     HOST: 'http://localhost:48271/',
     GTK2_RC_FILES: '/etc/gtk-2.0/gtkrc:/home/knut/.gtkrc-2.0:/home/knut/.config/gtkrc-2.0',
     KONSOLE_DBUS_SERVICE: ':1.27',
     KONSOLE_PROFILE_NAME: 'Shell',
     GS_LIB: '/home/knut/.fonts',
     GTK_RC_FILES: '/etc/gtk/gtkrc:/home/knut/.gtkrc:/home/knut/.config/gtkrc',
     WINDOWID: '46137374',
     HANDSHAKE: 'true',
     OLDPWD: '/home/knut/.meteor/packages/velocity_meteor-tool/1.1.3_4/mt-os.linux.x86_64',
     MOBILE_DDP_URL: 'http://localhost:48271',
     LESS_TERMCAP_ue: '\u001b[0m',
     SHELL_SESSION_ID: '5b62efb4da2b4000b184a34b5f401648',
     GTK_MODULES: 'canberra-gtk-module',
     KDE_FULL_SESSION: 'true',
     USER: 'knut',
     LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:',
     USERNAME: 'knut',
     SESSION_MANAGER: 'local/localhost.localdomain:@/tmp/.ICE-unix/25071,unix/localhost.localdomain:/tmp/.ICE-unix/25071',
     PAGER: 'less',
     MOZ_PLUGIN_PATH: '/usr/lib/mozilla/plugins',
     LESS_TERMCAP_us: '\u001b[01;32m',
     DESKTOP_SESSION: 'plasma',
     MAIL: '/var/spool/mail/knut',
     PATH: '/home/knut/.meteor/packages/velocity_meteor-tool/.1.1.3_4.e3silu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/knut/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl',
     METEOR_SETTINGS: '{}',
     sh: '/home/knut/Dokumente/Programming/meteor/playground/app',
     XDG_SESSION_TYPE: 'x11',
     PWD: '/home/knut/Dokumente/Programming/meteor/playground/app',
     PARENT_URL: 'http://localhost:3000/',
     MONGO_URL: 'mongodb://127.0.0.1:3001/cucumber',
     EDITOR: 'vi',
     KDE_SESSION_UID: '1000',
     LANG: 'de_DE.UTF-8',
     GDM_LANG: 'C',
     NODE_PATH: '',
     NODE_ENV: 'development',
     KONSOLE_DBUS_SESSION: '/Sessions/1',
     GDMSESSION: 'plasma',
     ROOT_URL: 'http://localhost:48271/',
     APP_ID: '8byf651dtkntr16pvx1p',
     se: '/home/knut/Dokumente/Programming/chrome-extensions/sh-chrome-extension',
     METEOR_PARENT_PID: '17065',
     HOME: '/home/knut',
     COLORFGBG: '15;0',
     XDG_SEAT: 'seat0',
     SHLVL: '2',
     KDE_SESSION_VERSION: '5',
     LANGUAGE: 'de',
     XCURSOR_THEME: 'breeze_cursors',
     SELENIUM_BROWSER: 'chrome',
     VELOCITY_DEBUG: '1',
     METEOR_PRINT_ON_LISTEN: 'true',
     XDG_SESSION_DESKTOP: 'plasma',
     LOGNAME: 'knut',
     LESS_TERMCAP_so: '\u001b[00;47;30m',
     XDG_DATA_DIRS: '/usr/share:/usr/share:/usr/local/share',
     DBUS_SESSION_BUS_ADDRESS: 'unix:abstract=/tmp/dbus-40FRdgEbrC,guid=52e890812c91470f763f74d45569a842',
     FRAMEWORK: 'cucumber',
     HTTP_FORWARDED_COUNT: '2',
     WINDOWPATH: '2',
     PORT: '27219',
     MONGO_OPLOG_URL: 'mongodb://127.0.0.1:3001/local',
     PROFILEHOME: '',
     XDG_RUNTIME_DIR: '/run/user/1000',
     DISPLAY: ':0',
     QT_PLUGIN_PATH: '/usr/lib/qt/plugins:/lib/kde5/plugins/',
     VELOCITY_MAIN_APP_PATH: '/home/knut/Dokumente/Programming/meteor/playground/app',
     XDG_CURRENT_DESKTOP: 'KDE',
     ROOT_URL_PATH: '',
     MOBILE_ROOT_URL: 'http://localhost:48271',
     COLORTERM: 'yes',
     LESS_TERMCAP_se: '\u001b[0m',
     XAUTHORITY: '/tmp/xauth-1000-_0' } }
[xolvio:cucumber] Chimp process forked with pid 17150
=> Started your app.

=> App running at: http://localhost:48271/
[velocity] Mirror started. Connecting via DDP to parent
Spawn script arguments:
parentPid: 17065
taskName: Chimp
command: /home/knut/.meteor/packages/velocity_meteor-tool/.1.1.3_4.e3silu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
commandArguments: [ '/home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp',
  '-r',
  '/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features',
  '--snippets',
  '--ddp=http://localhost:48271/',
  '--log=error',
  '--debug',
  '--screenshotsPath=/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/.screenshots',
  '--tags=@dev',
  '--browser=chrome',
  '--server',
  '--serverPort=8866' ]
pid: 17150
child.pid: 17152
[velocity] Mirror connected to parent. Registering mirror...
[velocity] Established connection with Velocity.
[chimp] Chimp server is running on port 8866 http://localhost:48271/
[chimp] Handshaking with DDP server
[xolvio:cucumber] Received handshake from Chimp. Connecting to hub
[chimp] Handshake complete, closing DDP connection
[xolvio:cucumber] Connected to hub.
Fixtures: finished populating database.
[xolvio:cucumber] Find and run triggered { '0': 
   { name: 'login.coffee',
     absolutePath: '/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features/step_definitions/login.coffee',
     relativePath: 'tests/cucumber/features/step_definitions/login.coffee',
     targetFramework: 'cucumber',
     lastModified: 1433023103942,
     _id: '/home/knut/Dokumente/Programming/meteor/playground/app/tests/cucumber/features/step_definitions/login.coffee' } }
[xolvio:cucumber] Running in batch-features mode.
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start

[chimp][selenium] hub can be seen at http://localhost:34181/wd/hub
Debug: internal, implementation, error 
    Error: Uncaught error: not found: java
    at Function.whichSync [as sync] (/home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/which/which.js:136:9)
    at Object.start (/home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/start.js:45:27)
    at /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/lib/selenium.js:127:14
    at /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/async/lib/async.js:251:17
    at /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/async/lib/async.js:154:25
    at /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/async/lib/async.js:248:21
    at /home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/async/lib/async.js:612:34
    at Object._onImmediate (/home/knut/.meteor/packages/xolvio_cucumber/.0.8.6.11gxwst++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:211:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
[xolvio:cucumber] Bad response from Chimp server.
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp] Finished interrupting processes
```

**Comment by samhatoum** [comment]
glad it helped. Install Java and chrome will work :)
