### ISSUE TITLE
Having issues with Meteor.userId when running inside phantomJs

### ISSUE THREAD

**Issue by orlaqp** [xolvio/meteor-cucumber#126]
First of all, great work! I am enjoying BDD!

I have an issue when running phatomJS though. Let me show you:

I have a scenario defined like this:

```cucumber
Feature: Sign Up

    As a guest
    I want to sign up for a user account
    So that I can start using the system

    Background:
         Given I am a new user
         And I navigate to "/sign-up"

    @dev
    Scenario: Sign up info is complete
        When Enter all information
        Then I should see the following message "Successful Registration! Please check your email and follow the instructions."
```

the steps definition that are used by this feature are the following:

```coffeescript
@Given /^I am a new user$/, ->
            @server.call 'reset'

@When /^I navigate to "([^"]*)"$/, (relativePath, callback) ->
            @client
                .url(url.resolve(process.env.ROOT_URL, relativePath))
                .call(callback)

@When /^Enter all information$/, (cb) ->
            @client
                .setValue('#at-field-email', 'email@address.com')
                .setValue('#at-field-companyName', 'Company Name')
                .setValue('#at-field-password', 'PASS01')
                .setValue('#at-field-password_again', 'PASS01')
                .click('#at-btn')
                .call(cb)
```

Note: When the user click #at-btn useraccounts:core take cover and add a new user to the system

This definition runs perfectly in firefox but when I run it using phantomJS (the default) and useraccounts:semantic-ui I get this:

```node
Exception while invoking method 'ATCreateUserServer' Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at Object.Meteor.userId (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/accounts-base.js:276:11)
    at /private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/app/modules/security/server/account-callbacks.coffee.js:27:40
    at /private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/accounts-base.js:1268:10
    at Array.forEach (native)
    at Function._.each._.forEach (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/underscore.js:139:11)
    at Object.Accounts.insertUserDoc (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/accounts-base.js:1267:5)
    at createUser (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/accounts-password.js:817:19)
    at Object.Accounts.createUser (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/accounts-password.js:875:10)
    at [object Object].Meteor.methods.ATCreateUserServer (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/useraccounts_core.js:1345:35)
    at Object.methods.rateLimit.callFunctionsInQueue (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/matteodem_easy-security.js:113:39)
    at /private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/matteodem_easy-security.js:157:25
    at /private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/matteodem_easy-security.js:133:13
    at [object Object]._.extend.withValue (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/meteor.js:989:17)
    at /private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/meteor.js:406:45
    at runWithEnvironment (/private/var/folders/qz/wng1k_8n19z1t1g0x1gvvcvh0000gn/T/meteor-test-runxrtwov/.meteor/local/build/programs/server/packages/meteor.js:1041:24)
    Then I should see the following message "Successful Registration! Please check your email and follow the instructions." # features/sign-up.feature:40
      AssertionError: expected 'Internal server error' to deeply equal 'Successful Registration! Please check your email and follow the instructions.'
        at [object Object].assertEqual (/Users/orlaqp/.meteor/packages/xolvio_cucumber/.0.8.9.p2yndu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/chai/lib/chai/core/assertions.js:439:19)
        at [object Object].ctx.(anonymous function) (/Users/orlaqp/.meteor/packages/xolvio_cucumber/.0.8.9.p2yndu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/chai/lib/chai/utils/addMethod.js:40:25)

```

Any idea what is going on here? Any help would be very appreciate it, thanks!

**Comment by orlaqp** [comment]
Never mind it was my fault in the validateNewUser callback
