### ISSUE TITLE
"Uncaught error: not found: java" on v0.11

### ISSUE THREAD

**Issue by jamiecollinson** [xolvio/meteor-cucumber#160]
Just upgraded to v0.11 and getting the following error:

```
[xolvio:cucumber] Bad response from Chimp server.
Debug: internal, implementation, error 
    Error: Uncaught error: not found: java
    at Function.whichSync [as sync] (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\which\which.js:136:9)
    at Object.start (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\lib\start.js:45:27)
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\lib\selenium.js:133:14
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:708:13
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:49:16
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:263:32
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:40:16
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:705:17
    at Object._onImmediate (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.0\npm\node_modules\chimp\node_modules\selenium-standalone\lib\install.js:211:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by samhatoum** [comment]
- Try a restart if you haven't already. 0.10.x had a nasty bug with processes hanging around. 

- Do you have Java installed? I'm assuming yes if 0.10.0 worked.

- Has it become corrupt? Maybe try to reinstall Java

**Comment by jamiecollinson** [comment]
Tried a restart and full reinstall of meteor. Reverting to 0.10.0 works
fine, so I don't think it's a corruption issue.

I didn't think I had java installed at all, but have just left my office
and won't be able to check until tomorrow. Is it installed be selenium
standalone?

I'm running on Windows 8.1 if that makes any difference, though a colleague
had the same issue on OS X.

**Comment by samhatoum** [comment]
OK I'd love to see the debug log from both machines as that will help me find the error

**Comment by jamiecollinson** [comment]
Here's the debug log (on 0.11.1 now rather than 0.11.0):

```
Spawn script arguments:
parentPid: 3236
taskName: cucumber
command: meteor.bat
commandArguments: [ 'run',
  '--test-app',
  '--port',
  '51297',
  '--include-tests',
  'cucumber/fixtures',
  '--settings',
  'C:\\Users\\JAMIE~1.COL\\AppData\\Local\\Temp\\tmp-4808hgbt8PytFB3.tmp',
  '--raw-logs',
  '--release',
  'velocity:METEOR@1.1.0.2_3' ]
pid: 5284
child.pid: 3060
=> Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)

[[[[[ C:\Users\jamie.collinson\projects\realtimecrm ]]]]]

=> Started proxy.
[sanjo:long-running-child-process]: Exposing imports for testing purposes
[velocity] adding velocity core
[xolvio:cucumber] Mirror server is initializing
[xolvio:cucumber] Starting Chimp
[xolvio:cucumber] Screenshots dir is C:\Users\jamie.collinson\projects\realtimecrm\tests\cucumber\.screenshots
[xolvio:cucumber] Starting Chimp with C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\bin\chimp [ 'C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\packages\\xolvio_cucumber\\0.11.1\\npm\\node_modules\\chimp\\bin\\chimp',
  '-r',
  'C:\\Users\\jamie.collinson\\projects\\realtimecrm\\tests\\cucumber\\features',
  '--snippets',
  '--ddp=http://localhost:51297/',
  '--log=error',
  '--debug',
  '--screenshotsPath=C:\\Users\\jamie.collinson\\projects\\realtimecrm\\tests\\cucumber\\.screenshots',
  '--tags=@dev',
  '--browser=firefox',
  '--server',
  '--serverPort=8866' ] { cwd: 'C:\\Users\\jamie.collinson\\projects\\realtimecrm\\tests\\cucumber',
  stdio: 'inherit',
  env: 
   { PORT: '26010',
     MIRROR_PORT: '51297',
     HOST: 'http://localhost:51297/',
     ROOT_URL_PATH: '',
     ROOT_URL: 'http://localhost:51297/',
     FRAMEWORK: 'cucumber',
     MONGO_URL: 'mongodb://127.0.0.1:3001/cucumber',
     PARENT_URL: 'http://localhost:3000/',
     IS_MIRROR: 'true',
     HANDSHAKE: 'true',
     VELOCITY_MAIN_APP_PATH: 'C:\\Users\\jamie.collinson\\projects\\realtimecrm',
     METEOR_SETTINGS: '{}',
     ALLUSERSPROFILE: 'C:\\ProgramData',
     APPDATA: 'C:\\Users\\jamie.collinson\\AppData\\Roaming',
     architecture: '64',
     ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
     CMDER_ROOT: 'C:\\Users\\jamie.collinson\\Downloads\\cmder',
     CMDER_START: '',
     CommonProgramFiles: 'C:\\Program Files (x86)\\Common Files',
     'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
     CommonProgramW6432: 'C:\\Program Files\\Common Files',
     COMPUTERNAME: 'SID-4785',
     ComSpec: 'C:\\Windows\\system32\\cmd.exe',
     ConEmuANSI: 'ON',
     ConEmuAnsiLog: '',
     ConEmuArgs: '/Icon "C:\\Users\\jamie.collinson\\Downloads\\cmder\\icons\\cmder.ico" /Title Cmder /LoadCfgFile "C:\\Users\\jamie.collinson\\Downloads\\cmder\\config\\ConEmu.xml"',
     ConEmuBackHWND: '0x000202C8',
     ConEmuBaseDir: 'C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5\\ConEmu',
     ConEmuBuild: '140707',
     ConEmuConfig: '',
     ConEmuDir: 'C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5',
     ConEmuDrawHWND: '0x000102CC',
     ConEmuDrive: 'C:',
     ConEmuHooks: 'Enabled',
     ConEmuHWND: '0x000602B8',
     ConEmuPID: '188',
     ConEmuServerPID: '2020',
     ConEmuWorkDir: 'C:\\Users\\jamie.collinson',
     ConEmuWorkDrive: 'C:',
     FP_NO_HOST_CHECK: 'NO',
     git_install_root: 'C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit',
     HOME: 'c:\\users\\jamie.collinson\\',
     HOMEDRIVE: 'C:',
     HOMEPATH: '\\Users\\jamie.collinson',
     JAVA_HOME: 'C:\\Program Files\\Java\\jre1.8.0_45',
     LOCALAPPDATA: 'C:\\Users\\jamie.collinson\\AppData\\Local',
     LOGONSERVER: '\\\\SID-4785',
     METEOR_INSTALLATION: 'C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\',
     NODE_PATH: 'C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\packages\\velocity_meteor-tool\\1.1.3_4\\mt-os.windows.x86_32\\dev_bundle\\server-lib\\node_modules',
     NUMBER_OF_PROCESSORS: '4',
     OS: 'Windows_NT',
     Path: 'C:\\Program Files\\Vim\\vim74;C:\\Users\\jamie.collinson\\Downloads\\cmder\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\mingw\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\cmd;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\share\\vim\\vim74;C:\\Users\\jamie.collinson\\Downloads\\cmder;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\ProgramData\\chocolatey\\bin;C:\\Python27;C:\\Program Files (x86)\\nodejs\\;C:\\tools\\python2;C:\\tools\\python2-x86_32;C:\\Program Files\\OpenVPN\\bin;C:\\tools\\python-x86_32;C:\\Program Files\\Java\\jre1.8.0_45\\bin;C:\\tools;C:\\Users\\jamie.collinson\\AppData\\Roaming\\npm;C:\\tools\\python2-x86_32\\Scripts;C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\;C:\\Users\\jamie.collinson\\AppData\\Local\\atom\\bin',
     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
     PLINK_PROTOCOL: 'ssh',
     PROCESSOR_ARCHITECTURE: 'x86',
     PROCESSOR_ARCHITEW6432: 'AMD64',
     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel',
     PROCESSOR_LEVEL: '6',
     PROCESSOR_REVISION: '4501',
     ProgramData: 'C:\\ProgramData',
     ProgramFiles: 'C:\\Program Files (x86)',
     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
     ProgramW6432: 'C:\\Program Files',
     PROMPT: 'C\bL\bI\bN\bK\b \b$E[1;32;40m$P$S{git}$S$_$E[1;30;40m{lamb}$S$E[0m',
     PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
     PUBLIC: 'C:\\Users\\Public',
     SELENIUM_BROWSER: 'firefox',
     SystemDrive: 'C:',
     SystemRoot: 'C:\\Windows',
     TEMP: 'C:\\Users\\JAMIE~1.COL\\AppData\\Local\\Temp',
     TERM: 'cygwin',
     TMP: 'C:\\Users\\JAMIE~1.COL\\AppData\\Local\\Temp',
     USERDOMAIN: 'SID-4785',
     USERDOMAIN_ROAMINGPROFILE: 'SID-4785',
     USERNAME: 'jamie.collinson',
     USERPROFILE: 'C:\\Users\\jamie.collinson',
     VELOCITY_DEBUG: '1',
     VS110COMNTOOLS: 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\',
     VS120COMNTOOLS: 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\',
     windir: 'C:\\Windows',
     __COMPAT_LAYER: 'RunAsAdmin Installer',
     MOBILE_DDP_URL: 'http://localhost:51297',
     MOBILE_ROOT_URL: 'http://localhost:51297',
     MONGO_OPLOG_URL: 'mongodb://127.0.0.1:3001/local',
     APP_ID: '1k86yn61cn1p0j5pwis8',
     NODE_ENV: 'development',
     HTTP_FORWARDED_COUNT: '2',
     METEOR_SHELL_DIR: 'C:\\Users\\JAMIE~1.COL\\AppData\\Local\\Temp\\meteor-test-run7fokln\\.meteor\\local\\shell',
     METEOR_PARENT_PID: '2176',
     METEOR_PRINT_ON_LISTEN: 'true',
     PATH: 'C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\packages\\velocity_meteor-tool\\1.1.3_4\\mt-os.windows.x86_32\\dev_bundle\\bin:C:\\Program Files\\Vim\\vim74;C:\\Users\\jamie.collinson\\Downloads\\cmder\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\mingw\\bin;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\cmd;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\msysgit\\share\\vim\\vim74;C:\\Users\\jamie.collinson\\Downloads\\cmder;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\Users\\jamie.collinson\\Downloads\\cmder\\vendor\\conemu-maximus5;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\ProgramData\\chocolatey\\bin;C:\\Python27;C:\\Program Files (x86)\\nodejs\\;C:\\tools\\python2;C:\\tools\\python2-x86_32;C:\\Program Files\\OpenVPN\\bin;C:\\tools\\python-x86_32;C:\\Program Files\\Java\\jre1.8.0_45\\bin;C:\\tools;C:\\Users\\jamie.collinson\\AppData\\Roaming\\npm;C:\\tools\\python2-x86_32\\Scripts;C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\;C:\\Users\\jamie.collinson\\AppData\\Local\\atom\\bin' } }
[xolvio:cucumber] Chimp process forked with pid 5392
Spawn script arguments:
parentPid: 2176
taskName: Chimp_8866
command: C:\Users\jamie.collinson\AppData\Local\.meteor\packages\velocity_meteor-tool\1.1.3_4\mt-os.windows.x86_32\dev_bundle\bin\node.exe
commandArguments: [ 'C:\\Users\\jamie.collinson\\AppData\\Local\\.meteor\\packages\\xolvio_cucumber\\0.11.1\\npm\\node_modules\\chimp\\bin\\chimp',
  '-r',
  'C:\\Users\\jamie.collinson\\projects\\realtimecrm\\tests\\cucumber\\features',
  '--snippets',
  '--ddp=http://localhost:51297/',
  '--log=error',
  '--debug',
  '--screenshotsPath=C:\\Users\\jamie.collinson\\projects\\realtimecrm\\tests\\cucumber\\.screenshots',
  '--tags=@dev',
  '--browser=firefox',
  '--server',
  '--serverPort=8866' ]
pid: 5392
child.pid: 2856
=> Started your app.

=> App running at: http://localhost:51297/
   Type Control-C twice to stop.

[velocity] Mirror started. Connecting via DDP to parent
[velocity] Mirror connected to parent. Registering mirror...
[velocity] Established connection with Velocity.
[chimp] Running npm install
[chimp] stdout: 
[chimp] stderr: 
[chimp] Chimp server is running on port 8866 http://localhost:51297/
[chimp] Handshaking with DDP server
[xolvio:cucumber] Received handshake from Chimp.
[xolvio:cucumber] Connecting to hub
[chimp] Handshake complete, closing DDP connection
[xolvio:cucumber] Connected to hub.
[xolvio:cucumber] Find and run triggered { '0': 
   { name: 'maintenance_mode.feature',
     absolutePath: '/C/Users/jamie.collinson/projects/realtimecrm/tests/cucumber/features/admin/maintenance_mode.feature',
     relativePath: 'tests/cucumber/features/admin/maintenance_mode.feature',
     targetFramework: 'cucumber',
     lastModified: 1436863436268,
     _id: '/C/Users/jamie.collinson/projects/realtimecrm/tests/cucumber/features/admin/maintenance_mode.feature' } }
[xolvio:cucumber] Running in batch-features mode.
[33m[xolvio:cucumber] Cucumber is running[39m
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:51333/wd/hub
Debug: internal, implementation, error 
    Error: Uncaught error: not found: java
    at Function.whichSync [as sync] (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\which\which.js:136:9)
    at Object.start (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\lib\start.js:45:27)
[chimp] interrupting
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\lib\selenium.js:133:14
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:708:13
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:49:16
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:263:32
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:40:16
    at C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\node_modules\async\lib\async.js:705:17
    at Object._onImmediate (C:\Users\jamie.collinson\AppData\Local\.meteor\packages\xolvio_cucumber\0.11.1\npm\node_modules\chimp\node_modules\selenium-standalone\lib\install.js:211:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
[31m[xolvio:cucumber] Bad response from Chimp server.[39m { [Error: failed [500] {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}] stack: [Getter] }
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp][selenium] interrupt called
[chimp][selenium] not stopping selenium server
[chimp] Finished interrupting processes
```

**Comment by jamiecollinson** [comment]
I didn't have JRE8 installed (which didn't seem to be required for 0.10.0). I've just manually installed JRE8 and tests now run, so perhaps it was previously included and no longer is?

In any case it looks like the solution is to ensure you've manually installed java.
