### ISSUE TITLE
Error: An element could not be located in cucumber-meteor-tutorial

### ISSUE THREAD

**Issue by byrne-yan** [xolvio/meteor-cucumber#173]
When i followed the cucumber-meteor-tutorial, following errors occured:
```
1 scenario (1 failed)
4 steps (1 failed, 2 skipped, 1 passed)
[chimp][hooks] Starting AfterFeatures
[chimp][hooks] Ending browser session
[chimp][session-manager] watch / server mode are true, not killing session
[chimp][hooks] Ended browser sessions
[chimp][hooks] Finished AfterFeatures

[chimp][cucumber] Closed with code 2
[chimp] finished rerun
[chimp] Finished running async processes with errors
Error: An element could not be located on the page using the given search parameters.
  at Object.<anonymous> (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/lib/commands/setValue.js:44:19)
  at Object.safeExecute (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/lib/utils/safeExecute.js:22:24)
  at Object.WebdriverIO.resolve (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/lib/webdriverio.js:73:29)
  at /home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/lib/webdriverio.js:183:32
  at _fulfilled (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:820:54)
  at self.promiseDispatch.done (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:849:30)
  at Promise.promise.promiseDispatch (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:782:13)
  at /home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:590:44
  at runSingle (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:123:13)
  at flush (/home/byrne/.meteor/packages/xolvio_cucumber/.0.12.2.izw9g5++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/webdriverio/node_modules/q/q.js:111:13)
  at process._tickDomainCallback (node.js:486:13)

```
# meteor list
```
accounts-password  1.1.1  Password support for accounts
accounts-ui        1.1.5  Simple templates to add login widgets to an app
autopublish        1.0.3  Publish the entire database to all clients
insecure           1.0.3  Allow all database writes by default
meteor-platform    1.2.2  Include a standard set of Meteor packages in your app
xolvio:cucumber    0.12.2  CucumberJS for Velocity
```

**Comment by samhatoum** [comment]
which tutorial is this?

**Comment by byrne-yan** [comment]
https://github.com/mhurwi/cucumber-meteor-tutorial

**Comment by samhatoum** [comment]
Can you please file a bug on his repo :)

**Comment by byrne-yan** [comment]
Sure
