### ISSUE TITLE
Updated Cucumber doesn't work on CodeShip

### ISSUE THREAD

**Issue by sircharleswatson** [xolvio/meteor-cucumber#181]
I've been playing around with this for hours but can't solve the problem.

First, I run the tests with
```
xolvio:cucumber@0.10.0
velocity:html-reporter@0.6.2
```
It runs just fine and my tests pass (As they should)

Then if I update cucumber to `0.12.3` the build fails. 

Here is the log:
```
=> Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)

stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
=> Babel active on file extensions: es6.js, es6, jsx
I20150802-03:25:49.848(0)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150802-03:25:49.849(0)? ** you still have autopublish turned on. Because autopublish is still
I20150802-03:25:49.850(0)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150802-03:25:49.850(0)? ** will still be sent to all clients.
I20150802-03:25:49.850(0)? **
I20150802-03:25:49.850(0)? ** Turn off autopublish by removing the autopublish package:
I20150802-03:25:49.850(0)? **
I20150802-03:25:49.850(0)? **   $ meteor remove autopublish
I20150802-03:25:49.851(0)? **
I20150802-03:25:49.851(0)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150802-03:25:49.851(0)? ** for each collection that you want clients to see.
I20150802-03:25:49.851(0)? 
I20150802-03:25:49.851(0)? [velocity] is in continuous integration mode
I20150802-03:25:51.394(0)? [velocity] cucumber is starting a mirror at http://localhost:47228/.
I20150802-03:25:51.435(0)? [velocity] You can see the mirror logs at: tail -f /home/rof/src/github.com/TaskHero/TaskHero/.meteor/local/log/cucumber.log
I20150802-03:25:52.291(0)? [cucumber.log] Spawn script arguments:
I20150802-03:25:52.292(0)? [cucumber.log] parentPid: 4607
I20150802-03:25:52.292(0)? [cucumber.log] taskName: cucumber
I20150802-03:25:52.292(0)? [cucumber.log] command: meteor
I20150802-03:25:52.292(0)? [cucumber.log] commandArguments: [ 'run',
I20150802-03:25:52.292(0)? [cucumber.log]   '--test-app',
I20150802-03:25:52.292(0)? [cucumber.log]   '--port',
I20150802-03:25:52.293(0)? [cucumber.log]   '47228',
I20150802-03:25:52.293(0)? [cucumber.log]   '--include-tests',
I20150802-03:25:52.293(0)? [cucumber.log]   'cucumber/fixtures',
I20150802-03:25:52.293(0)? [cucumber.log]   '--settings',
I20150802-03:25:52.293(0)? [cucumber.log]   '/tmp/tmp-60023x8sqLUafzrV.tmp',
I20150802-03:25:52.293(0)? [cucumber.log]   '--raw-logs',
I20150802-03:25:52.293(0)? [cucumber.log]   '--release',
I20150802-03:25:52.294(0)? [cucumber.log]   'velocity:METEOR@1.1.0.2_3' ]
I20150802-03:25:52.294(0)? [cucumber.log] pid: 6026
I20150802-03:25:52.294(0)? [cucumber.log] child.pid: 6028
I20150802-03:26:00.298(0)? [cucumber.log] => Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)
I20150802-03:26:00.298(0)? [cucumber.log] 
I20150802-03:26:00.298(0)? [cucumber.log] [[[[[ ~/src/github.com/TaskHero/TaskHero ]]]]]
I20150802-03:26:00.298(0)? [cucumber.log] 
I20150802-03:26:00.298(0)? [cucumber.log] => Started proxy.
I20150802-03:26:06.303(0)? [cucumber.log] => Babel active on file extensions: es6.js, es6, jsx
I20150802-03:26:09.304(0)? [cucumber.log] [sanjo:long-running-child-process]: Exposing imports for testing purposes
I20150802-03:26:09.304(0)? [cucumber.log] ** You've set up some data subscriptions with Meteor.publish(), but
I20150802-03:26:09.304(0)? [cucumber.log] ** you still have autopublish turned on. Because autopublish is still
I20150802-03:26:09.304(0)? [cucumber.log] ** on, your Meteor.publish() calls won't have much effect. All data
I20150802-03:26:09.304(0)? [cucumber.log] ** will still be sent to all clients.
I20150802-03:26:09.305(0)? [cucumber.log] **
I20150802-03:26:09.305(0)? [cucumber.log] ** Turn off autopublish by removing the autopublish package:
I20150802-03:26:09.305(0)? [cucumber.log] **
I20150802-03:26:09.308(0)? [cucumber.log] **   $ meteor remove autopublish
I20150802-03:26:09.309(0)? [cucumber.log] **
I20150802-03:26:09.310(0)? [cucumber.log] ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150802-03:26:09.310(0)? [cucumber.log] ** for each collection that you want clients to see.
I20150802-03:26:09.310(0)? [cucumber.log] 
I20150802-03:26:09.310(0)? [cucumber.log] [velocity] is in continuous integration mode
I20150802-03:26:10.305(0)? [cucumber.log] Spawn script arguments:
I20150802-03:26:10.306(0)? [cucumber.log] parentPid: 6028
I20150802-03:26:10.306(0)? [cucumber.log] taskName: Chimp_8866
I20150802-03:26:10.306(0)? [cucumber.log] command: /home/rof/.meteor/packages/velocity_meteor-tool/.1.1.3_4.pcpqys++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
I20150802-03:26:10.306(0)? [cucumber.log] commandArguments: [ '/home/rof/.meteor/packages/xolvio_cucumber/.0.12.3.e8lue4++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp',
I20150802-03:26:10.306(0)? [cucumber.log]   '-r',
I20150802-03:26:10.306(0)? [cucumber.log]   '/home/rof/src/github.com/TaskHero/TaskHero/tests/cucumber/features',
I20150802-03:26:10.307(0)? [cucumber.log]   '--snippets',
I20150802-03:26:10.307(0)? [cucumber.log]   '--ddp=http://localhost:47228/',
I20150802-03:26:10.307(0)? [cucumber.log]   '--log=error',
I20150802-03:26:10.307(0)? [cucumber.log]   '--screenshotsOnError=true',
I20150802-03:26:10.307(0)? [cucumber.log]   '--screenshotsPath=/home/rof/src/github.com/TaskHero/TaskHero/tests/cucumber/.screenshots',
I20150802-03:26:10.307(0)? [cucumber.log]   '--tags=~@ignore',
I20150802-03:26:10.307(0)? [cucumber.log]   '--server',
I20150802-03:26:10.308(0)? [cucumber.log]   '--serverPort=8866' ]
I20150802-03:26:10.308(0)? [cucumber.log] pid: 6344
I20150802-03:26:10.308(0)? [cucumber.log] => Started your app.
I20150802-03:26:10.308(0)? [cucumber.log] 
I20150802-03:26:10.308(0)? [cucumber.log] => App running at: http://localhost:47228/
I20150802-03:26:10.308(0)? [cucumber.log] child.pid: 6346
I20150802-03:26:10.309(0)? [cucumber.log] [velocity] Established connection with Velocity.
I20150802-03:26:12.307(0)? [cucumber.log] => Server modified -- restarting...
I20150802-03:26:12.307(0)?                                    
I20150802-03:26:12.307(0)? [cucumber.log] SyntaxError: Unexpected token U
I20150802-03:26:12.307(0)? [cucumber.log]     at Object.parse (native)
I20150802-03:26:12.308(0)? [cucumber.log]     at Request._callback (/home/rof/.meteor/packages/xolvio_cucumber/.0.12.3.e8lue4++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/ddp/lib/ddp-client.js:376:23)
I20150802-03:26:12.308(0)? [cucumber.log]     at Request.self.callback (/home/rof/.meteor/packages/xolvio_cucumber/.0.12.3.e8lue4++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/ddp/node_modules/request/request.js:344:22)
I20150802-03:26:12.308(0)? [cucumber.log]     at Request.emit (events.js:98:17)
I20150802-03:26:12.308(0)? [cucumber.log]     at Request.<anonymous> (/home/rof/.meteor/packages/xolvio_cucumber/.0.12.3.e8lue4++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/ddp/node_modules/request/request.js:1239:14)
I20150802-03:26:12.308(0)? [cucumber.log]     at Request.emit (events.js:117:20)
I20150802-03:26:12.308(0)? [cucumber.log]     at IncomingMessage.<anonymous> (/home/rof/.meteor/packages/xolvio_cucumber/.0.12.3.e8lue4++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/ddp/node_modules/request/request.js:1187:12)
I20150802-03:26:12.308(0)? [cucumber.log]     at IncomingMessage.emit (events.js:117:20)
I20150802-03:26:12.308(0)? [cucumber.log]     at _stream_readable.js:944:16
I20150802-03:26:12.309(0)? [cucumber.log]     at process._tickDomainCallback (node.js:486:13)
I20150802-03:26:17.309(0)? [cucumber.log] [sanjo:long-running-child-process]: Exposing imports for testing purposes
I20150802-03:26:17.309(0)? [cucumber.log] ** You've set up some data subscriptions with Meteor.publish(), but
I20150802-03:26:17.309(0)? [cucumber.log] ** you still have autopublish turned on. Because autopublish is still
I20150802-03:26:17.309(0)? [cucumber.log] ** on, your Meteor.publish() calls won't have much effect. All data
I20150802-03:26:17.309(0)? [cucumber.log] ** will still be sent to all clients.
I20150802-03:26:17.309(0)? [cucumber.log] **
I20150802-03:26:17.310(0)? [cucumber.log] ** Turn off autopublish by removing the autopublish package:
I20150802-03:26:17.310(0)? [cucumber.log] **
I20150802-03:26:17.310(0)? [cucumber.log] **   $ meteor remove autopublish
I20150802-03:26:17.310(0)? [cucumber.log] **
I20150802-03:26:17.310(0)? [cucumber.log] ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150802-03:26:17.310(0)? [cucumber.log] ** for each collection that you want clients to see.
I20150802-03:26:17.310(0)? [cucumber.log] 
I20150802-03:26:17.311(0)? [cucumber.log] [velocity] is in continuous integration mode
[TypeError: Cannot call method 'join' of ]
I20150802-03:26:19.309(0)? [cucumber.log] => Meteor server restarted
I20150802-03:26:19.309(0)? [cucumber.log] [velocity] Established connection with Velocity.
I20150802-03:26:19.309(0)? [cucumber.log] [xolvio:cucumber] Cucumber is running
I20150802-03:26:19.309(0)? [cucumber.log] [xolvio:cucumber] Bad response from Chimp server. { [Error: connect ECONNREFUSED] stack: [Getter] }
FAILURE
```

**Comment by sircharleswatson** [comment]
One other note.

In reference to [this](https://github.com/xolvio/meteor-cucumber/issues/171#issuecomment-126974269)

If I ssh into the server it's running on, the tests/build fail the first time but pass the second time.

**Comment by frosario** [comment]
I am experiencing the same intermittent failure when running tests on TravisCI:
https://github.com/ecohealthalliance/mantle/issues/73

**Comment by sircharleswatson** [comment]
`xolvio:cucumber@0.13.1` fixed this for me!

@frosario try updating and see if it works for you too.

**Comment by frosario** [comment]
No such luck for me. It looks like it hangs after:
`[velocity] Triggering queued startup functions`

This is the travis build:
https://travis-ci.org/ecohealthalliance/mantle/builds/73990566#L227

The commit where I ran `meteor update` to make sure I had all of the latest version:
https://github.com/ecohealthalliance/mantle/commit/1cd702dceede1ca7c0f2a5f4ec3da03ad4463a17

**Comment by sircharleswatson** [comment]
@frosario there is a 0.13.3 now, might want to try that. but otherwise, you're right. I'll close this now since it's resolved for me.

**Comment by samhatoum** [comment]
it's 0.13.2 and @frosario can you try with that please? Also export `CUCUMBER_TAIL=1` please

**Comment by samhatoum** [comment]
@frosario please do open a new issue so I can keep an eye on it
