### ISSUE TITLE
Using Meteor in fixture seems to hang

### ISSUE THREAD

**Issue by g00glen00b** [xolvio/meteor-cucumber#186]
I added a file called `tests/cucumber/features/fixtures/testData.fixture.js`, containing the following:

    console.log("Hello world");

If I run the code, the fixture is correctly invoked, and I see the following in `.meteor/local/logs/cucumber.log`: 

    [xolvio:cucumber] Cucumber is running
    Hello world

However, as soon as I replace the fixture with the following:

    console.log("Hello world");

    Meteor.methods({
      "testData": function(messages) {
        messages.forEach(function(data) {
          Messages.insert({
            message: data[0],
            username: data[1],
            owner: data[2],
            time: moment(data[3], "HH:mm:ss").toDate()
          })
        });
      },
      "reset": function() {
        Messages.remove({});
      }
    });

    console.log("Hi");

Then the code seems to break, the logging statement at the bottom does not work at all, if I look at the log file I only see the Hello world being printed and nothing else. If I take a look at the Velocity HTML reporter, the `cucumber - mirror` state keeps loading.

As soon as I start using `Meteor` in the fixture, things go wrong, even the following does not execute:

    console.log(Meteor);

To give some details about my system, I'm running on Mac OS X, running xolvio:cucumber 0.6.6.

**Comment by g00glen00b** [comment]
I see that Cucumber 0.6.6 is an old version, I installed 0.13.3 and now it shows an error in stead (probably it broke because of that error in older versions). The error I get is:

```
/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:24
    throw(e);
          ^
ReferenceError: Meteor is not defined
  at Object.<anonymous> (/Workspaces/workspace/ucll-workshop-meteor/tests/cucumber/features/fixtures/testData.fixture.js:3:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:60:29
  at Array.forEach (native)
  at Object.wrapper (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:59:15)
  at Object.initializer (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:21:41)
  at Object.Library (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/support_code/library.js:131:25)
  at Object.getSupportCodeLibrary (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
  at Object.getSupportCodeLibrary (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/configuration.js:51:52)
  at Object.getSupportCodeLibrary (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime.js:42:46)
  at Object.start (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime.js:17:37)
  at Object.<anonymous> (/Users/Dimitri/.meteor/packages/xolvio_cucumber/.0.13.3.1xw2qbq++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:19:11)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by samhatoum** [comment]
move the fixtures up on level to `/cucumber/fixtures`
