### ISSUE TITLE
"Full Cucumber run" causes error

### ISSUE THREAD

**Issue by Sanjo** [xolvio/meteor-cucumber#196]
It seems that the connection wasn't initialized.

Reproduce:
1. Have a feature with the @dev tag
2. Start the app
3. Wait until the feature has initially run
4. Click the "Full Cucumber run" button in the html reporter

I also have CHIMP_OPTIONS set to '--watch=@dev --debug=true --log=verbose'

```
Exception while invoking method 'runAll' TypeError: Cannot call method 'call' of undefined
    at _runSingleExecutionMode (packages/xolvio:cucumber/src/mirror-server.js:120:1)
    at [object Object].Meteor.methods.runAll (packages/xolvio:cucumber/src/mirror-server.js:49:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:52:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:51:1)
    at packages/ddp/livedata_server.js:546:1
```

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#103
