### ISSUE TITLE
Console.log clashes

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/meteor-cucumber#20]
I am primarily using console to view the tests results.
The problem appears, when more than one framework is being used at the same time and frameworks are outputting information at the same time (I am using jasmine and cucumber). It becomes quite confusing (see below - actually not the worst example). 

Is it possible to implement more streamlined console output, when it's clear which framework is outputting which information? I guess the ConsoleReporter should be replaced by something like VelocityConsoleReporter, which would run as singleton on Velocity and be reported to via DDP. 

```bash
W20150106-14:44:56.111(11)? (STDERR) connections property is deprecated. Use getConnections() method
I20150106-14:44:56.470(11)? [velocity-mirror] [velocity-mirror] Mirror is initializing...
I20150106-14:44:56.470(11)? 
I20150106-14:44:57.168(11)? Started
I20150106-14:44:57.449(11)? ...........[velocity-mirror] [velocity-mirror] Mirror is ready.
I20150106-14:44:57.449(11)? 
I20150106-14:44:57.829(11)? .....................[xolvio:cucumber] Cucumber is running
I20150106-14:44:58.703(11)? ..........................
I20150106-14:44:58.703(11)? 
I20150106-14:44:58.703(11)? 57 specs, 0 failures
I20150106-14:44:58.703(11)? Finished in 1.535 seconds
I20150106-14:44:59.258(11)? ..F.
I20150106-14:44:59.258(11)? 
I20150106-14:44:59.258(11)? (::) failed steps (::)
I20150106-14:44:59.259(11)? 
I20150106-14:44:59.259(11)? AssertionError: "" == "intentional failure"
I20150106-14:44:59.259(11)?   at WebdriverIO.<anonymous> (/Users/tomi/Documents/Programming/Hugo/First/tests/cucumber/features/step_definitions/sampleSteps.js:27:18)
I20150106-14:44:59.267(11)?   at /Users/tomi/.meteor/packages/xolvio_webdriver/.0.1.3.1rovq7h++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/chainit/index.js:137:22
I20150106-14:44:59.267(11)?   at RequestHandler.<anonymous> (/Users/tomi/.meteor/packages/xolvio_webdriver/.0.1.3.1rovq7h++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/RequestHandler.js:223:13)
I20150106-14:44:59.267(11)?   at Request.self.callback (/Users/tomi/.meteor/packages/xolvio_webdriver/.0.1.3.1rovq7h++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:121:22)
I20150106-14:44:59.267(11)?   at Request.emit (events.js:98:17)
I20150106-14:44:59.267(11)?   at Request.<anonymous> (/Users/tomi/.meteor/packages/xolvio_webdriver/.0.1.3.1rovq7h++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:978:14)
I20150106-14:44:59.267(11)?   at Request.emit (events.js:117:20)
I20150106-14:44:59.268(11)?   at IncomingMessage.<anonymous> (/Users/tomi/.meteor/packages/xolvio_webdriver/.0.1.3.1rovq7h++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:929:12)
I20150106-14:44:59.268(11)?   at IncomingMessage.emit (events.js:117:20)
I20150106-14:44:59.268(11)?   at _stream_readable.js:943:16
I20150106-14:44:59.268(11)?   at process._tickCallback (node.js:419:13)
I20150106-14:44:59.268(11)? 
I20150106-14:44:59.268(11)? 
I20150106-14:44:59.269(11)? Failing scenarios:
I20150106-14:44:59.269(11)? /Users/tomi/Documents/Programming/Hugo/First/tests/cucumber/features/sample.feature:11 # Scenario: 
I20150106-14:44:59.269(11)? 
I20150106-14:44:59.269(11)? 1 scenario (1 failed)
I20150106-14:44:59.269(11)? 3 steps (1 failed, 2 passed)
```

**Comment by samhatoum** [comment]
Agreed. This needs an elegant solution. I'll keep this hear to track.

**Comment by samhatoum** [comment]
Velocity now has a separate log file that you can tail separately for each framework mirror.
