### ISSUE TITLE
Firefox crashes

### ISSUE THREAD

**Issue by myknbani** [xolvio/meteor-cucumber#207]
Hi, I'm using 0.14 rc2 of xolvio:cucumber, and it cannot run tests in Firefox.  Chrome works fine.  

I used the command:  `SELENIUM_BROWSER=firefox VELOCITY_DEBUG=1 meteor`
I also tried `CHIMP_OPTIONS="--browser=firefox"` and tried combining both options.  
If it helps, I'm using Firefox-KDE 38.0.6.  Thanks! :D

Here is the log:  

```
{ [Error: Bad request
Command duration or timeout: 76 milliseconds
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'valar-morghulis', ip: '192.168.10.139', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.5-1-MANJARO', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.firefox.FirefoxDriver]
  message: 'Bad request\nCommand duration or timeout: 76 milliseconds\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'valar-morghulis\', ip: \'192.168.10.139\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.0.5-1-MANJARO\', java.version: \'1.8.0_05\'\nDriver info: org.openqa.selenium.firefox.FirefoxDriver',
  type: 'RuntimeError' }
Error: Bad request
  at Object.Future.wait (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/fibers/future.js:420:15)
  at Object.<anonymous> (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/@xolvio/fiber-utils/index.js:48:19)
  at Object.<anonymous> (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/session-manager.js:131:21)
  at initBrowser (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/hooks.js:66:15)
  at /home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/hooks.js:107:7
  at /home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:100:43

    - - - - -
Command duration or timeout: 76 milliseconds
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'valar-morghulis', ip: '192.168.10.139', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.5-1-MANJARO', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
  at new ErrorHandler.RuntimeError (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/webdriverio/lib/utils/RequestHandler.js:168:25)
  at Request.self.callback (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/home/mikenbani/.meteor/packages/xolvio_cucumber/.0.14.0-rc.2.1ttthm1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/@xolvio/sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:486:13)

[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined, null ] ]
[chimp] Responding to /run request with:
undefined
[chimp] finished rerun
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Tue, 08 Sep 2015 05:51:57 GMT',
     connection: 'keep-alive' },
  data: null }
[chimp] interrupting
[chimp] 2 processes to interrupt

```

**Comment by myknbani** [comment]
I think the solution is some fishy-looking edit to the /etc/hosts file as mentioned here:  https://github.com/SeleniumHQ/selenium/issues/431

The "workaround" works for me.
