### ISSUE TITLE
How to create test data in Before hook

### ISSUE THREAD

**Issue by wackazong** [xolvio/meteor-cucumber#44]
Hi there, I am trying to create some test data in a Before hook as such

```
    this.Before(Meteor.bindEnvironment(function (scenario, callback) {
      var world = helper.world;
      var next = arguments[arguments.length - 1];

      Meteor.users.remove({});

      Accounts.createUser({
        username: "test1name",
        email: "test11@asdf.com",
        password: "test1pass",
        profile: {
          name: "Test1"
        }
      });

      console.log('BEFORE '+ scenario.getName(), "(" + scenario.getUri() + ":" + scenario.getLine() + ")");

      world.browser.
          init().
          setViewportSize({
            width: 1280,
            height: 1024
          }).
          call(next);
    }));
```

Two things that I cannot solve at the moment:

1) The database I am accessing here is meteor, not cucumber. How can I change that? I want to modify the database of the mirror application

2) When I add Accounts.createUser, cucumber constantly restarts and I never get a report. The application is restarted after this log output:

````
I20150220-01:20:13.520(1)? [xolvio:cucumber] Cucumber is running
I20150220-01:20:13.843(1)? [xolvio:webdriver] getGhostDriver called
I20150220-01:20:13.845(1)? [xolvio:webdriver] Phantom is already running, not starting a new one
I20150220-01:20:14.124(1)? BEFORE A user can login with valid information (/Users/alexanderwalter/Development/willmit/tests/cucumber/features/loginAndLogout.feature:10)
I20150220-01:20:18.781(1)? ....F.[xolvio:webdriver] getGhostDriver called
I20150220-01:20:18.782(1)? [xolvio:webdriver] Phantom is already running, not starting a new one
I20150220-01:20:18.880(1)? BEFORE A user cannot log in with invalid information (/Users/alexanderwalter/Development/willmit/tests/cucumber/features/loginAndLogout.feature:15)
I20150220-01:20:22.647(1)? ......[xolvio:webdriver] getGhostDriver called
I20150220-01:20:22.648(1)? [xolvio:webdriver] Phantom is already running, not starting a new one
I20150220-01:20:22.744(1)? BEFORE When a user logs in, password requirements must not be checked (/Users/alexanderwalter/Development/willmit/tests/cucumber/features/loginAndLogout.feature:20)
W20150220-01:20:26.465(1)? (STDERR) 
=> Exited with code: 8
W20150220-01:20:26.467(1)? (STDERR) AssertionError: "object" == "string"
W20150220-01:20:26.468(1)? (STDERR)   at WebdriverIO.<anonymous> (/Users/alexanderwalter/Development/willmit/tests/cucumber/features/step_definitions/loginSteps.js:61:18)
W20150220-01:20:26.469(1)? (STDERR)   at WebdriverIO.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/PromiseHandler.js:146:26)
W20150220-01:20:26.470(1)? (STDERR)   at /Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/chainit/index.js:137:22
W20150220-01:20:26.470(1)? (STDERR)   at /Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/commands/getText.js:84:9
W20150220-01:20:26.471(1)? (STDERR)   at /Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/async/lib/async.js:157:25
W20150220-01:20:26.472(1)? (STDERR)   at WebdriverIO.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/commands/getText.js:64:21)
W20150220-01:20:26.473(1)? (STDERR)   at WebdriverIO.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/PromiseHandler.js:146:26)
W20150220-01:20:26.474(1)? (STDERR)   at /Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/chainit/index.js:137:22
W20150220-01:20:26.475(1)? (STDERR)   at RequestHandler.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/RequestHandler.js:223:13)
W20150220-01:20:26.476(1)? (STDERR)   at Request.self.callback (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:121:22)
W20150220-01:20:26.477(1)? (STDERR)   at Request.emit (events.js:98:17)
W20150220-01:20:26.477(1)? (STDERR)   at Request.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:978:14)
W20150220-01:20:26.478(1)? (STDERR)   at Request.emit (events.js:117:20)
W20150220-01:20:26.479(1)? (STDERR)   at IncomingMessage.<anonymous> (/Users/alexanderwalter/.meteor/packages/xolvio_webdriver/.0.1.8.121fef5++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:929:12)
W20150220-01:20:26.480(1)? (STDERR)   at IncomingMessage.emit (events.js:117:20)
W20150220-01:20:26.480(1)? (STDERR)   at _stream_readable.js:943:16
W20150220-01:20:26.481(1)? (STDERR)   at process._tickDomainCallback (node.js:463:13)
W20150220-01:20:26.482(1)? (STDERR)           
I20150220-01:20:26.493(1)? ....               
```

**Comment by wackazong** [comment]
It seems that if I add the Accounts.addUser call, the assertions of the tests get thrown as real errors and cause the restart of the application.

**Comment by Sanjo** [comment]
1) Create a DDP connection with the mirror:

```javascript
module.exports = function () {
    var connection = DDP.connect(
      Package['xolvio:cucumber'].cucumber.mirror.rootUrl
    );

    // ...
}
```

2) Create a new local package that has a Meteor method (I used the name `resetTestingEnvironment`) that creates the user. Add `debugOnly: true` to the Package.describe block. This flag will load the package only in development mode (for security).

3) The this.Before hook can look like this:

```javascript
    this.Before(Meteor.bindEnvironment(function () {
      var world = helper.world;
      var next = arguments[arguments.length - 1];
      var init = function () {
        world.browser.
          init().
          setViewportSize({
            width: 1280,
            height: 1024
          }).
          call(next);
      };

      var resetTestingEnvironment = Meteor.bindEnvironment(function () {
        connection.call('resetTestingEnvironment', init);
      });

      resetTestingEnvironment();
    }));
```

**Comment by adeubank** [comment]
This is awesome! Thank you, @Sanjo. I was running into a similar problem and thought it was something that I was doing wrong. This solved it for me.

**Comment by wackazong** [comment]
Hi, thanks. When I do it like this, the assertion is thrown as an error and meteor restarts the app. If I do not execute the callback of the Before function in the callback function of the method call then everything is fine. But then I can not wait for the async execution of the call.

**Comment by wackazong** [comment]
Sorry, of course no callback is needed because we are executing on the server. The method can be executed synchronously. All these different servers make my head spin a bit...

**Comment by samhatoum** [comment]
I totally hear you!

**Comment by wackazong** [comment]
Great, works for me now with b4d69a6bdeb24c7c03258ae3e32d70441809d511 . Thanks.
