### ISSUE TITLE
Getting 'Exception in callback of async function: TypeError: Cannot call method 'toString' of undefined' with default test

### ISSUE THREAD

**Issue by chompomonim** [xolvio/meteor-cucumber#67]
I just did `meteor add xolvio:cucumber` and then added default test (by clicking on button in velocity panel). Now I'm getting this error:

```
I20150407-00:13:11.737(3)? [xolvio:cucumber] Cucumber is running
I20150407-00:13:11.881(3)? Exception in callback of async function: TypeError: Cannot call method 'toString' of undefined
I20150407-00:13:11.881(3)?     at Object.parse (/Users/jaro/.meteor/packages/xolvio_cucumber/.0.5.5.1vnxmns++os+web.browser+web.cordova/npm/node_modules/cucumber/lib/cucumber/parser.js:15:52)
I20150407-00:13:11.882(3)?     at Object.getFeatures (/Users/jaro/.meteor/packages/xolvio_cucumber/.0.5.5.1vnxmns++os+web.browser+web.cordova/npm/node_modules/cucumber/lib/cucumber/runtime.js:30:35)
I20150407-00:13:11.882(3)?     at Object.start (/Users/jaro/.meteor/packages/xolvio_cucumber/.0.5.5.1vnxmns++os+web.browser+web.cordova/npm/node_modules/cucumber/lib/cucumber/runtime.js:16:37)
I20150407-00:13:11.882(3)?     at _rerunCucumber (packages/xolvio:cucumber/server.js:132:1)
I20150407-00:13:11.882(3)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by samhatoum** [comment]
Hi

Can you try 0.6.0-rc.1

That's the new version that will be published soon

Thanks

**Comment by chompomonim** [comment]
How to do that?

**Comment by samhatoum** [comment]
edit your `.meteor/packages` file to say `xolvio:cucumber@0.6.0-rc.1`

**Comment by chompomonim** [comment]
Unfortunately still getting error:
```
package-version-parser            removed from your project
sanjo:long-running-child-process  added, version 1.0.3
sanjo:meteor-version              removed from your project
velocity:chokidar                 added, version 0.12.6_1
velocity:core+                    upgraded from 0.4.5 to 0.6.0-rc.4
velocity:meteor-internals         added, version 1.1.0_5
xolvio:cucumber                   upgraded from 0.5.5 to 0.6.0-rc.1

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
W20150407-14:20:23.006(3)? (STDERR)           
W20150407-14:20:23.007(3)? (STDERR) /Users/jaro/.meteor/packages/meteor-tool/.1.1.3.spsu4v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150407-14:20:23.008(3)? (STDERR) 						throw(ex);
W20150407-14:20:23.008(3)? (STDERR) 						      ^
W20150407-14:20:23.008(3)? (STDERR) TypeError: Cannot set property 'start' of undefined
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:882:21
W20150407-14:20:23.008(3)? (STDERR)     at Array.forEach (native)
W20150407-14:20:23.008(3)? (STDERR)     at _.each._.forEach (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:139:11)
W20150407-14:20:23.008(3)? (STDERR)     at Function._.extend (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:879:5)
W20150407-14:20:23.008(3)? (STDERR)     at DEBUG (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:449:5)
W20150407-14:20:23.008(3)? (STDERR)     at DEBUG (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:539:3)
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:543:4
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:768:3
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/boot.js:222:10
W20150407-14:20:23.008(3)? (STDERR)     at Array.forEach (native)
```

**Comment by chompomonim** [comment]
Now I'm getting errors because of upgraded velocity.core:

```
package-version-parser            removed from your project
sanjo:long-running-child-process  added, version 1.0.3
sanjo:meteor-version              removed from your project
velocity:chokidar                 added, version 0.12.6_1
velocity:core+                    upgraded from 0.4.5 to 0.6.0-rc.4
velocity:meteor-internals         added, version 1.1.0_5
xolvio:cucumber                   upgraded from 0.5.5 to 0.6.0-rc.1

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
W20150407-14:20:23.006(3)? (STDERR)           
W20150407-14:20:23.007(3)? (STDERR) /Users/jaro/.meteor/packages/meteor-tool/.1.1.3.spsu4v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150407-14:20:23.008(3)? (STDERR) 						throw(ex);
W20150407-14:20:23.008(3)? (STDERR) 						      ^
W20150407-14:20:23.008(3)? (STDERR) TypeError: Cannot set property 'start' of undefined
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:882:21
W20150407-14:20:23.008(3)? (STDERR)     at Array.forEach (native)
W20150407-14:20:23.008(3)? (STDERR)     at _.each._.forEach (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:139:11)
W20150407-14:20:23.008(3)? (STDERR)     at Function._.extend (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/underscore.js:879:5)
W20150407-14:20:23.008(3)? (STDERR)     at DEBUG (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:449:5)
W20150407-14:20:23.008(3)? (STDERR)     at DEBUG (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:539:3)
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:543:4
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_node-soft-mirror.js:768:3
W20150407-14:20:23.008(3)? (STDERR)     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/boot.js:222:10
W20150407-14:20:23.008(3)? (STDERR)     at Array.forEach (native)
```

**Comment by Sanjo** [comment]
Do you use another testing framework besides xolvio:cucumber?

**Comment by chompomonim** [comment]
Yes, `mike:mocha`

**Comment by Sanjo** [comment]
Ok, right now the latest version of mike:mocha does not work with the new velocity:core. I've made a breaking change. I will inform him that he should release a new version.

For testing xolvio:cucumber you would need to remove mike:mocha temporarly.

**Comment by chompomonim** [comment]
Ok. Thanks.

After removing mike:mocha package, xolvio:cucumber started without errors but...

I'm getting an error after adding sample tests:

```
Exception while invoking method 'velocity/copySampleTests' TypeError: Arguments to path.join must be strings
I20150407-14:50:45.399(3)?     at path.js:360:15
I20150407-14:50:45.399(3)?     at Array.filter (native)
I20150407-14:50:45.399(3)?     at Object.exports.join (path.js:358:36)
I20150407-14:50:45.399(3)?     at Object.pathJoin (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_meteor-internals.js:660:16)
I20150407-14:50:45.399(3)?     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_core.js:588:36
I20150407-14:50:45.400(3)?     at Array.forEach (native)
I20150407-14:50:45.400(3)?     at [object Object].Meteor.methods.velocity/copySampleTests (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/velocity_core.js:587:21)
I20150407-14:50:45.400(3)?     at [object Object].methodMap.(anonymous function) (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2495:30)
I20150407-14:50:45.400(3)?     at maybeAuditArgumentChecks (/Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
I20150407-14:50:45.400(3)?     at /Users/jaro/Dev/Meteor/toic/.meteor/local/build/programs/server/packages/ddp.js:1476:20
```

**Comment by samhatoum** [comment]
Can you please try with `meteor add xolvio:cucumber@0.6.0-rc.7` please? Please be sure to see the [breaking changes](https://github.com/xolvio/meteor-cucumber#breaking-changes) section.

**Comment by chompomonim** [comment]
@samhatoum now I have no errors with xolvio:cucumber@0.6.0-rc.7. Closing the tasks.
