### ISSUE TITLE
CUCUMBER_NODES - value interpreted as a string

### ISSUE THREAD

**Issue by djhi** [xolvio/meteor-cucumber#70]
When I try to set the CUCUMBER_NODES environment variable to 4, I get the following error:
```
Error: Match error: Expected number, got string in field nodes
W20150408-16:53:33.736(2)? (STDERR)     at checkSubtree (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/check.js:177:13)
W20150408-16:53:33.736(2)? (STDERR)     at /home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/check.js:314:9
W20150408-16:53:33.736(2)? (STDERR)     at Function._.each._.forEach (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/underscore.js:147:22)
W20150408-16:53:33.736(2)? (STDERR)     at checkSubtree (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/check.js:308:5)
W20150408-16:53:33.736(2)? (STDERR)     at check (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/check.js:50:5)
W20150408-16:53:33.736(2)? (STDERR)     at [object Object].Meteor.methods.velocity/mirrors/request (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/velocity_core.js:1094:7)
W20150408-16:53:33.737(2)? (STDERR)     at maybeAuditArgumentChecks (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
W20150408-16:53:33.737(2)? (STDERR)     at /home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/ddp.js:2358:18
W20150408-16:53:33.737(2)? (STDERR)     at [object Object]._.extend.withValue (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/meteor.js:989:17)
W20150408-16:53:33.737(2)? (STDERR)     at [object Object]._.extend.apply (/home/gildas/projects/payfacile/.meteor/local/build/programs/server/packages/ddp.js:2357:45)
```

`parseInt` ?

**Comment by samhatoum** [comment]
Ah yes, thank you. I'll fix that. 

The parallel still won't work though, there's another issue in the mirror I have to fix first. Is next on my list though :)

**Comment by djhi** [comment]
:+1: 
Congratulations for this version btw, it rocks !

**Comment by samhatoum** [comment]
Fixes in rc.8 - but still won't run parallel. Soon!

**Comment by djhi** [comment]
II know parallel testing does not work yet but in case it is important when I run meteor with this environment variable, I get this error:

```
=> App running at: http://localhost:40215/
[velocity] Established connection with Velocity.
Exception in callback of async function: Error: Access denied [403]
    at Object.Future.wait (/home/gildas/.meteor/packages/velocity_meteor-tool/.1.1.3_2.ervu25++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object]._.extend.apply (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:3964:21)
    at [object Object].Mongo.Collection.(anonymous function) (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/mongo.js:3911:26)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/aldeed_collection2.js:189:23)
    at _findAndRun.findAndRun (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/xolvio_cucumber.js:208:28)
    at _findAndRun (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/xolvio_cucumber.js:217:7)
    at runWithEnvironment (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/meteor.js:1041:24)
    - - - - -
    at [object Object]._.extend._livedata_result (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:4557:23)
    at onMessage (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:3318:12)
    at runWithEnvironment (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/meteor.js:1041:24)
    at /tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/meteor.js:1054:14
    at /tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:245:9
    at Array.forEach (native)
    at Function._.each._.forEach (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/underscore.js:139:11)
    at /tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:244:9
    at /tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/ddp.js:220:11
    at runWithEnvironment (/tmp/meteor-test-runzktk0f/.meteor/local/build/programs/server/packages/meteor.js:1041:24)
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
```

**Comment by lgandecki** [comment]
same here.. Exception in callback of async function: Error: Access denied [403]
  at Object.Future.wait (/home/meteorci/.meteor/packages/velocity_meteor-tool/.1.1.3_2.167tc0l++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
