### ISSUE TITLE
Logs when returning promises are confusing

### ISSUE THREAD

**Issue by carlosbaraza** [xolvio/meteor-cucumber#71]
I am currently trying to migrate to 0.6 but I am experimenting multiple issues. I already reported an issue on the velocity core meteor-velocity/velocity#312 . However, now I found a strange behaviour on the cucumber logs:

```
Feature: Edit profile

  As a user
  I want to edit my profile information
  So that it is displayed in the business card of my page


  Scenario:                                           # features/admin/profile_edit.feature:7
    Given I am a new user                             # features/admin/profile_edit.feature:8
    When I navigate to "/"                            # features/admin/profile_edit.feature:9
    Then I should see the title "intentional failure" # features/admin/profile_edit.feature:10
      AssertionError: expected 'personalbrand' to deeply equal 'intentional failure'
        at [object Object].assertEqual (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai/lib/chai/core/assertions.js:439:19)
        at [object Object].ctx.(anonymous function) (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
        at WebdriverIO.<anonymous> (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai-as-promised/lib/chai-as-promised.js:310:26)
        at /Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/lib/utils/PromiseHandler.js:85:52
        at process._tickDomainCallback (node.js:486:13)

    Then I should see the title "intentional failure" # features/admin/profile_edit.feature:10
    After
      RuntimeError: RuntimeError
           Problem: Variable Resource Not Found - {"headers":{"Accept":"application/json","Connection":"keep-alive","User-Agent":"webdriverio/webdriverio/2.4.5","content-length":"0","host":"localhost:56518"},"httpVersion":"1.1","method":"DELETE","url":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","urlParsed":{"anchor":"","query":"","file":"27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","directory":"/session/","path":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","relative":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","queryKey":{},"chunks":["session","27d4e8c0-e08e-11e4-ac83-cbc131fd35dd"]}}

           Callstack:
           -> session("delete","27d4e8c0-e08e-11e4-ac83-cbc131fd35dd")
           -> endAll()



(::) failed steps (::)

AssertionError: expected 'personalbrand' to deeply equal 'intentional failure'
  at [object Object].assertEqual (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai/lib/chai/core/assertions.js:439:19)
  at [object Object].ctx.(anonymous function) (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
  at WebdriverIO.<anonymous> (/Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/chai-as-promised/lib/chai-as-promised.js:310:26)
  at /Users/baraza/.meteor/packages/xolvio_cucumber/.0.6.0-rc.8.dh4mdc++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/lib/utils/PromiseHandler.js:85:52
  at process._tickDomainCallback (node.js:486:13)


RuntimeError: RuntimeError
     Problem: Variable Resource Not Found - {"headers":{"Accept":"application/json","Connection":"keep-alive","User-Agent":"webdriverio/webdriverio/2.4.5","content-length":"0","host":"localhost:56518"},"httpVersion":"1.1","method":"DELETE","url":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","urlParsed":{"anchor":"","query":"","file":"27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","directory":"/session/","path":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","relative":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/27d4e8c0-e08e-11e4-ac83-cbc131fd35dd","queryKey":{},"chunks":["session","27d4e8c0-e08e-11e4-ac83-cbc131fd35dd"]}}

     Callstack:
     -> session("delete","27d4e8c0-e08e-11e4-ac83-cbc131fd35dd")
     -> endAll()


Failing scenarios:
/tests/cucumber/features/admin/profile_edit.feature:7 # Scenario:

1 scenario (1 failed)
5 steps (2 failed, 3 passed)
```

Even if this behaviour is strange, it still works and the issue is not blocking.

Thank you guys for this work, now the tests look way more clear, I am loving this new 0.6.
Carlos.

**Comment by samhatoum** [comment]
The 5 steps include two hidden ones! They are before and after. You can see the code from these steps here: 
* [before](https://github.com/xolvio/cuke-monkey/blob/develop/lib/cucumberjs/hooks.js#L37)
* [after](https://github.com/xolvio/cuke-monkey/blob/develop/lib/cucumberjs/hooks.js#L81)

I will add this info to the readme. Thanks for reporting!

**Comment by samhatoum** [comment]
I *think* the steps only show up when there are errors

**Comment by carlosbaraza** [comment]
Ah, ok, I have missed that then :). When there is a failure, in the html-reporter I get a weird _After undefined_ step and no information about the actual failure, is it normal?

![screen shot 2015-04-12 at 00 10 49](https://cloud.githubusercontent.com/assets/1270425/7103449/6c70ceee-e0a8-11e4-9987-065071874cc9.png)

**Comment by samhatoum** [comment]
Short answer, no! I think it needs a little work on our side to make it report better. This is happening because the promise is being returned. If you use callbacks instead this won't happen.

@Sanjo this is the error reporting issue I was talking about with promises

**Comment by samhatoum** [comment]
@carlosbaraza I'll keep this thread open. You can get better error reporting using callbacks (the "normal" cucumberjs way) until we fix this

**Comment by carlosbaraza** [comment]
@Sanjo ok, great to know that I am not crazy nor a newbie :P

Thank you anyway for these packages. I am having great time working with your tools.
Carlos.

**Comment by samhatoum** [comment]
I've *slightly* improved these errors. We'll soon release a synchronous version of chimp that will hopefully make these go away
