### ISSUE TITLE
Please help me better understand how to use Cucumber

### ISSUE THREAD

**Issue by mbabauer** [xolvio/meteor-cucumber#77]
This probably doesn't belong as an "issue", but I am not sure where else to post this.  I have tried getting help through StackOverflow with limited success, so I am hoping the folks here can help enlighten me.

I am trying to get some end-to-end testing done using the meteor-cucumber package.  I am new to Cucumber, WebDriver.IO, and Chai, but I can read APIs so I thought I could muddle through this stuff.

Where I am struggling is that nothing seems to work the way it is documented.  For instance, in the meteor-cucumber README.MD it is states that Chai and Chai-as-promised is already loaded.  The Chai documentation [here](http://chaijs.com/guide/styles/) has an `assert`, but when I try something like this:
```javascript
this.browser
  .saveScreenshot('screenshots/afterNewClientDone.png')
  .elements('.clientExpansionCaret', function(err, res) {
    assert.isUndefined(err);
    // do something...
  });
```
I get an error saying:
```
    And I should be able to create a new Client named "Test Client" # features/admins_create_form.feature:15
      ReferenceError: assert is not defined
        at WebdriverIO.<anonymous> (/tests/cucumber/features/step_definitions/admin_client_steps.js:33:11)
        at WebdriverIO.<anonymous> (/Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
        at /Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/chainit/index.js:137:22
        at RequestHandler.<anonymous> (/Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/lib/utils/RequestHandler.js:223:13)
        at Request.self.callback (/Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:121:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:978:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/Users/mbauer/.meteor/packages/xolvio_cucumber/.0.6.6.1f7q5ye++os+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:929:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:486:13)
```

So, I tried adding `var assert = require('chai').assert;` at the top, but then the test runner freezes at `[xolvio:cucumber] Cucumber is running`  and never does anything.  The same happened when I tried to add underscore as well.

Past that, I am getting strange results.  the `.elements()` example above passes a "result" object to the callback function, but the `results.value` doesn't look like a real DOM element, and none of the calls like `.getText()` or `.innerHTML` seem to work.  I have many other places where things just haven't seemed to work at all like the APIs seem to suggest they should.

As a single developer trying to incorporate this into my development, it is hard to justify to myself the benefits of spending time on these tests when I spend 3 days just trying to get a simple test done where I add something on the page and then click the newly added DOM elements.  Maybe some additional, more "real-world" examples would help by showing what good practices look like and how to handle certain situations in your tests?

**Comment by samhatoum** [comment]
I'm adding `chai` to the `global` scope in the next release so you can say `var assert = global.chai.assert`.

**Comment by mbabauer** [comment]
Sounds great.  Do you know why the tests are freezing when I try to import a library like underscore?

**Comment by samhatoum** [comment]
I don't off hand, but if you can create a small reproducible repo, I can
look

**Comment by robertwalsh0** [comment]
I've also seen tests freeze while importing a library into a steps file eg:
```
  var moment = require('moment');
```

**Comment by samhatoum** [comment]
have you guys seen this: 

https://github.com/xolvio/meteor-cucumber#adding-npm-modules

**Comment by mbabauer** [comment]
That's what I did.  I put the package.json under /test/cucumber, then did a `var _ = require('underscore')`.  I also tried with jquery and chai.

**Comment by samhatoum** [comment]
ok, and to double check you also ran `npm install` in the same dir?

Do you see a `node_modules` dir with those packages inside it?

**Comment by robertwalsh0** [comment]
@samhatoum That fixed it. It's always embarrassing when the answer is in the manual :(

**Comment by samhatoum** [comment]
@robertwalsh0 no worries :)

@mbabauer did this work for you wit `npm install`?

**Comment by mbabauer** [comment]
Yup, that worked like a champ!  Thanks for following up with me.  I didn't get the last response for some reason.
