### ISSUE TITLE
SyntaxError: Unexpected token a

### ISSUE THREAD

**Issue by DominikGuzei** [xolvio/meteor-cucumber#96]
Hey there,
Sometimes when I have a step that calls `@browser.url('…')` I get this weird error:
```
SyntaxError: Unexpected token a
        at Object.parse (native)
        at [object Object].<anonymous> (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.8.0.1by8sdn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/lib/cucumberjs/hooks.js:118:24)
        at [object Object].emit (events.js:117:20)
        at RequestHandler.<anonymous> (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.8.0.1by8sdn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/lib/utils/RequestHandler.js:164:40)
        at Request.self.callback (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.8.0.1by8sdn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:121:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.8.0.1by8sdn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:978:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/Users/dominik/.meteor/packages/xolvio_cucumber/.0.8.0.1by8sdn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:929:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:486:13)

[cuke-monkey][hooks] browser error event - capturing screenshot

events.js:72
        throw er; // Unhandled 'error' event
              ^
```

The problem is, that it occurs randomly and can often be resolved by restarting the application.
Do you have any idea what the underlying problem could be?

**Comment by DominikGuzei** [comment]
I should say that I use the `SELENIUM_BROWSER=chrome` flag :wink:

**Comment by samhatoum** [comment]
Looks like the real error is being hidden by a json parse error here: 
https://github.com/xolvio/cuke-monkey/blob/develop/lib/cucumberjs/hooks.js#L118

You can checkout https://github.com/xolvio/cuke-monkey and run meteor like this:
`CUKE_MONKEY_PATH=<path to cuke-monkey>/bin/cuke-monkey meteor` and add a debug message in the hooks. I'll improve the logging in the next release so it will try to parse instead of just parsing. I thought the `message` was always JSON but it looks like it can be something else!

**Comment by DominikGuzei** [comment]
Thanks, now I get more details:

```
[xolvio:cucumber] Cucumber is running
@accounts @projects @swatches @sharing
Feature: Sharing project colors

  In order to share my colors with developers
  As a designer
  I want to provide them with auto-generated CSS preprocessor variables

  @dev
  Scenario: Sharing colors as SASS variables                 # features/projects/sharing.feature:25
    Given a verified user named "dominik"                    # features/projects/sharing.feature:10
    And I am logged in as "dominik"                          # features/projects/sharing.feature:11
    And I have a project "Website" with these swatches:      # features/projects/sharing.feature:12
      | TITLE         | COLOR   |
      | simple        | #ff0000 |
      | With spaces   | #00ff00 |
      | special-chars | #fff    |
[cuke-monkey][hooks] browser error event - capturing screenshot
asynchronous script timeout: result was not received in 3 seconds
  (Session info: chrome=42.0.2311.152)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.9.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.28 seconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Macintosh.local', ip: '25.174.89.152', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_09'
Session ID: 7b8025da5ac0aeb4500f9b7bc43c5df0
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/cz/fnf__xc15sn5lg_drgbyfl9c0000gn/T/.org.chromium.Chromium.tOxYiw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.152, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    When I go to the project sharing screen for "Website"    # features/projects/sharing.feature:26
      SyntaxError: Unexpected token a
        at Object.parse (native)
        at [object Object].<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/lib/cucumberjs/hooks.js:119:24)
        at [object Object].emit (events.js:117:20)
        at RequestHandler.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/lib/utils/RequestHandler.js:164:40)
        at Request.self.callback (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:121:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:978:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:929:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:486:13)

[cuke-monkey][hooks] browser error event - capturing screenshot

events.js:72
unknown error: cannot take screenshot
from unknown error: Failed to capture tab: unknown error
JavaScript stack:
Error: Failed to capture tab: unknown error
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:37:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:73:7)
  (Session info: chrome=42.0.2311.152)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.9.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 70 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Macintosh.local', ip: '25.174.89.152', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_09'
Session ID: 7b8025da5ac0aeb4500f9b7bc43c5df0
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/cz/fnf__xc15sn5lg_drgbyfl9c0000gn/T/.org.chromium.Chromium.tOxYiw}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.152, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token u
  at Object.parse (native)
  at [object Object].<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/lib/cucumberjs/hooks.js:119:24)
  at [object Object].emit (events.js:117:20)
  at RequestHandler.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/lib/utils/RequestHandler.js:164:40)
  at Request.self.callback (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:121:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:978:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/dominik/work/projects/opensource/meteor/cucumber/cuke-monkey/node_modules/webdriverio/node_modules/request/request.js:929:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:486:13)

[cuke-monkey][monkey] Finished running async processes with errors
[xolvio:cucumber] Bad response from cuke-monkey server. Try rerunning
```

**Comment by samhatoum** [comment]
Looks like a chromedriver issue
https://code.google.com/p/chromedriver/issues/detail?id=1083

Perhaps switch to firefox / safari temporarily? Or maybe a previous version of chromedriver. You can do that in cuke-monkey also 
https://github.com/xolvio/cuke-monkey/blob/develop/lib/selenium.js#L58

should probably make that configurable!

**Comment by DominikGuzei** [comment]
Can I somehow disable the screenshots? I don't need that anyway, since I love inspecting the real page in chrome when something is wrong :wink:

**Comment by DominikGuzei** [comment]
The switch to firefox worked fine, so for now I can work with that :wink:

**Comment by samhatoum** [comment]
Good idea, I'll add tasks for chrome version and error screenshots

**Comment by samhatoum** [comment]
added a task to make this configurable. Closing
